### ISSUE TITLE
Error 100: File exists - /vagrant

### ISSUE THREAD

**Issue by glennk** [cloudfoundry/bosh-lite#109]
I followed the steps here and then used ./scripts/provision_cf

... all success ...

Deployment set to `/Users/grk/workspace/bosh-lite/manifests/cf-manifest.yml'
Config
             /Users/grk/.bosh_config

Director
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.2559.0 (fe0b2436)
  User       admin
  UUID       c5f8d0da-f8ac-4918-a1a3-0a846fb97d09
  CPI        warden
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

Deployment
  Manifest   /Users/grk/workspace/bosh-lite/manifests/cf-manifest.yml
- deploy_release
  ++ find /Users/grk/workspace/cf-release/releases -regex '.*cf-[0-9]{3}.yml'
  ++ sort
  ++ tail -n 1
- MOST_RECENT_CF_RELEASE=/Users/grk/workspace/cf-release/releases/cf-171.yml
- bosh upload release --skip-if-exists /Users/grk/workspace/cf-release/releases/cf-171.yml

$ bosh -n deploy
Getting deployment properties from director...
Compiling deployment manifest...

Director task 4
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:00)

  Started preparing package compilation > Finding packages to compile. Failed: File exists - /vagrant (00:00:00)

**Comment by acca** [comment]
I've ran into this error because I've renamed the path of my project. This caused vBox to share a folder which was not existent. Changing the share inside vBox and reloading the VM solved it.

**Comment by CrazydduGi** [comment]
@acca You save me!! Thanks

**Comment by ulsa** [comment]
I'm on vagrant 1.7.4, and in my case it was likely caused by me moving bosh-lite into a subfolder after 'vagrant up' had been run. As far as I can tell, just doing 'vagrant reload' solved it.

**Comment by EdwardStudy** [comment]
@ulsa I move the bosh-lite dir, so 'vagrant reload' is working.
