### ISSUE TITLE
provision_cf failure - not in gzip format (Zlib::GzipFile::Error)

### ISSUE THREAD

**Issue by chibi03** [cloudfoundry/bosh-lite#120]
I've been hitting the following error when trying to run the provision_cf script.

```
/home/samirah/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2334.0/lib/cli/stemcell.rb:27:in `initialize': not in gzip format (Zlib::GzipFile::Error)
```

Any ideas?

**Comment by alienbaby** [comment]
I also saw this error after running provision_cf without curl installed.  The provision failed, I installed curl, then hit this error. Turn out even though curl wasnt there an empty .tgz had been created.
