### ISSUE TITLE
[WARNING] cannot access director, trying 4 more times

### ISSUE THREAD

**Issue by dwatrous** [cloudfoundry/bosh-lite#143]
I am on Windows 7 using VirtualBox. When I follow the posted instructions I get the following output

C:\Users\watrous\Documents\GitHub\bosh-lite>bosh target 192.168.50.4 lite
Target already set to `←[0m←[32mBosh Lite Director←[0m'

C:\Users\watrous\Documents\GitHub\bosh-lite>bosh login
Your username: admin
Enter password: *****
←[0m←[33m[WARNING] cannot access director, trying 4 more times...←[0m
←[0m←[33m[WARNING] cannot access director, trying 3 more times...←[0m
←[0m←[33m[WARNING] cannot access director, trying 2 more times...←[0m
←[0m←[33m[WARNING] cannot access director, trying 1 more times...←[0m
←[0m←[31mcannot access director (execution expired)←[0m

I have verified that the VM is running. I can SSH into the instance and ping the IP 192.168.50.4. What can I do to troubleshoot this?

**Comment by meetgrinder** [comment]
Has there been any resolution to this? 
I'm trying on Ubuntu 14.04 (trusty). I've made upgrades to vagrant and virtualbox to no avail.
I've seen others with this problem on the internet. No clear identification of the problem or solution so far.

I was able to get PCF up on my mac laptop, but no success on the ubuntu as of yet.

**Comment by rikyreas14** [comment]
I tried bosh inside VM and still I am getting the same issue

**Comment by meetgrinder** [comment]
I ended up using VBoxManage to open a VM mgmt gui and increase the ram of my VM and got it to work 

Thanks fort he feedback rikyreas14
