### ISSUE TITLE
Unable to authenticate with cf

### ISSUE THREAD

**Issue by draganm** [cloudfoundry/bosh-lite#147]
After following all the steps to install using VirtualBox on a Mac OS X installation I've been unable to log in using CF command:

$ cf login
API endpoint: https://api.10.244.0.34.xip.io

Email> admin

Password> 
Authenticating...
Server error, status code: 500, error code: , message: 

Password> 
Authenticating...
Server error, status code: 500, error code: , message: 

...

Can't see any significant entries neither in the CloudController nor in UAA logs. Any idea what went wrong?

**Comment by ryunata** [comment]
Hi, I have the same issue. Any advice for solution? Thanks
