### ISSUE TITLE
Spiff for Ubuntu

### ISSUE THREAD

**Issue by sreelathakoye** [cloudfoundry/bosh-lite#161]
Hello,

Found Spiff for MacOSX and Linux, but for Ubuntu, i have tried same as for Linux, but that binary seems not working.
Is there any way to install spiff for Ubuntu.
Help in this would be great.

Thanks & Regards,
Sreelatha.

**Comment by laurentvaills** [comment]
The issue on pivotaltracker seems to have been deleted or is not public.
I get this : 
> Sorry, we couldn't find that story
> It may be in a project you haven't been invited to yet or it may have been deleted.

**Comment by dpb587-pivotal** [comment]
For posterity... make sure you are downloading the correct binary for your system from https://github.com/cloudfoundry-incubator/spiff/releases (or building yourself, if they're not listed).
