### ISSUE TITLE
bosh-lite locked to a broken version of the bosh_cli?

### ISSUE THREAD

**Issue by hiremaga** [cloudfoundry/bosh-lite#162]
see https://github.com/cloudfoundry-incubator/diego-release/issues/7#issuecomment-51989327

**Comment by gerhard** [comment]
@cppforlife I would very much like to have nothing but the bosh_cli bundled with bosh-lite so that I wouldn't be getting the dreaded `Loading the cli took n seconds, consider cleaning your gem environment`. How are you handling a lean bosh_cli gem environment?

**Comment by drnic** [comment]
You can "vagrant ssh" to access a version of bosh that's bundled inside




Also you could use bundler (Gemfile) to fix a version on the host machine.

**Comment by gerhard** [comment]
@drnic I need to use bosh from outside the VM.

I definitely agree that bosh_cli in Gemfile + `bundle install --bintubs` + `PATH=./bin:$PATH` is the best approach. I wanted to understand the reasons behind removing the Gemfile from the project. Maybe there is a better way of achieving a lean gem environment that bosh is happy with.

**Comment by drnic** [comment]
You don't need the bosh-lite repo per se. Make your own repo, and in the Vagrantfile plus Gemfile and you're good to go.

**Comment by drnic** [comment]
For example https://github.com/starkandwayne/concourse-bosh-lite is a bosh-lite with dedicated instructions to deploy concourse to it

**Comment by gerhard** [comment]
Makes sense, cheer :wink:
