### ISSUE TITLE
Undeclared dependency on Spiff

### ISSUE THREAD

**Issue by gavmor** [cloudfoundry/bosh-lite#197]
Running `bin/provision_cf` produces this error, and an empty `cf-manifest.yml`:

```
/Users/pivotal/workspace/cf-release/generate_deployment_manifest: line 17: spiff: command not found
Incorrect YAML structure in `/Users/pivotal/workspace/bosh-lite/manifests/cf-manifest.yml': expected Hash at the root
```

This was trivially overcome via the README from the spiff [repository](https://github.com/cloudfoundry-incubator/spiff)

```
brew tap xoebus/homebrew-cloudfoundry
brew install spiff
```

**Comment by bsideup** [comment]
@cppforlife would be cool if "provide_cf" script will fail if spiff is not found. I spent 1 hour trying to figure out why it's failing with "you must select deployment first" instead of informative "spiff not found" :)
