### ISSUE TITLE
gem install bosh_cli should install spliff

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/bosh-lite#207]
Because it's a hard dependency.

**Comment by jchesterpivotal** [comment]
This just bit me again for the third freaking time.

I don't really care who or what installs it. Every time I try to use bosh lite on a new machine it is **utterly broken** until I remember that I have to install spiff by myself.

**Comment by drnic** [comment]
I empathise with the challenging UX for new user/new machine though I also don't agree with bundling spiff in rubygems.




Perhaps a solution is to provide a bin script to fetch latest spiff for current OS




Eg https://github.com/starkandwayne/concourse-bosh-lite/blob/master/install_fly_cli.sh fetches a binary from a location and installs it locally




https://github.com/cloudfoundry-community/traveling-bosh/blob/master/Rakefile#L225 has some code for downloading spiff specifically.





Combine these together.
