### ISSUE TITLE
BOSH-Lite shutdown can leave stale state, breaking next startup

### ISSUE THREAD

**Issue by darthweino** [cloudfoundry/bosh-lite#211]
Observed with recent versions of BOSH-Lite AMI images ( tested here with v389).

BOSH-Lite can sometimes leave behind stale pid files for the director and workers, leaving monit to think services have come up when they haven't.

When programatically deploying from customised AMIs, we have repeatedly seen cases when the director has not started because another service has started with the pid previously associated with the director. This causes monit to think the service is running, when in fact it is not.

We have also seen the same behaviour in the workers ( bosh jobs appear perpetually 'queued') as shown below:

after a ```monit stop all```

```
root@agent-id-bosh-0:/var/vcap/sys/run# monit summary
The Monit daemon 5.2.4 uptime: 17m

Process 'nats'                      not monitored
Process 'redis'                     not monitored
Process 'blobstore_nginx'           not monitored
Process 'postgres'                  not monitored
Process 'director'                  not monitored
Process 'worker_1'                  not monitored
Process 'worker_2'                  not monitored
Process 'worker_3'                  not monitored
Process 'director_scheduler'        not monitored
Process 'director_nginx'            not monitored
Process 'health_monitor'            not monitored
Process 'cpi'                       not monitored
Process 'warden'                    not monitored
System 'system_agent-id-bosh-0'     not monitored
root@agent-id-bosh-0:/var/vcap/sys/run# find .
.
./postgres
./redis
./cpi
./health_monitor
./warden
./nats
./blobstore
./director
./director/worker_1.pid
./director/worker_2.pid
```
Notice the two remaining pid files for the workers that should have been removed.

The control scripts for these daemons may need some tweaking.

**Comment by cppforlife** [comment]
Fixed. Agent mounts tmpfs on /var/vcap/data/sys/run type tmpfs (rw,size=1m)
