### ISSUE TITLE
Multi Region support on AWS

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh-lite#213]

**Comment by cppforlife** [comment]
Could you elaborate what you meant?  Do you want us to provide AMIs in non-default region?

**Comment by longnguyen11288** [comment]
Currently bosh-lite on AWS is only on US-east. It would be nice if AMI was provided in the other regions as well.

**Comment by cppforlife** [comment]
Which region(s) are you most interested in?

**Comment by longnguyen11288** [comment]
I think any of the regions in the US would be useful

**Comment by drnic** [comment]
Ahhhhh.... I lost a few hours today not realising it wouldn't deploy into us-west-2 if I gave it a subnet ID in that region. Doh.

I also raised https://github.com/mitchellh/vagrant-aws/issues/401

**Comment by longnguyen11288** [comment]
Done!
