### ISSUE TITLE
bin/provision_cf should create security group for services

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/bosh-lite#217]
In cf-release, the [make_manifest](https://github.com/cloudfoundry/cf-release/blob/master/bosh-lite/make_manifest) script creates a security group for services. It would be helpful if the provision_cf script in this repo does the same - otherwise anyone using it will be unable to bind an app to their service without first creating a new security group.

**Comment by cppforlife** [comment]
Switched to using cf-release's scripts.
