### ISSUE TITLE
VMware boxes are no longer created/published

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-lite#228]
Commit 93e1ad90bc942c7bd2f85c7812e203b3b37d4715 stopped creating an publishing boxes for the VMware providers.  If the boxes won't be published, it seems like it makes sense to at least document the levels (bosh and warden) necessary to create a level that's compatible with the current boxes.

**Comment by cppforlife** [comment]
Fair enough we can add a readme mention for that.

**Comment by sykesm** [comment]
@cppforlife, it's been a little bit; any thoughts around publishing bosh and warden levels used in boxes? Thanks.

**Comment by cppforlife** [comment]
Done. See builds in the pipeline: http://lite.bosh-ci.cf-app.com:8080/jobs/new-box
