### ISSUE TITLE
./bin/provision_cf freezes my MacBook Air

### ISSUE THREAD

**Issue by olalonde** [cloudfoundry/bosh-lite#230]
I am trying to setup a PaaS type development environment locally on my MacBook Air (13-inch, Mid 2011 - 4gb memory) so that it mirrors my production environment and I can easily launch my web API and a bunch of related services in a simple command. I followed the instructions on how to setup bosh-lite without problem and `bosh login` works at this point.

I then try to install CloudFoundry using the `./bin/provision_cf` and it works fine up until the upload stage. At this point, my computer becomes completely unresponsive and I need to hard reboot it.

Is this normal? Does my computer have insufficient resources to run the CF release? Are there lighter solutions that would run on my laptop? Perhaps a docker based CF deployment if that makes sense? Does it exist?

**Comment by karlkfi** [comment]
Hard to say what would cause a lockup, but if I had to guess I'd say not enough RAM.

According to #203 it sounds like 16GB is recommended, 8GB likely minimum. We use 32GB here at Pivotal for our dev workstations.

**Comment by olalonde** [comment]
Ah, that's a bummer :-1: Are you aware of any CloudFoundry service that has a "free for development" plan?
