### ISSUE TITLE
Cannot vagrant up --provider=aws

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/bosh-lite#235]
I try to `vagrant up --provider=aws` and I get the following error

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* An access key ID must be specified via "access_key_id"
* A secret access key is required via "secret_access_key"
* vagrant_aws.config.ami_required
```

Output of `env | grep -i bosh`
```
BOSH_LITE_SUBNET_ID=[redacted]
BOSH_AWS_ACCESS_KEY_ID=[redacted]
BOSH_LITE_NAME=Vagrant
BOSH_LITE_PRIVATE_KEY=[redacted]
BOSH_AWS_SECRET_ACCESS_KEY=[redacted]
BOSH_LITE_SECURITY_GROUP=inception
BOSH_LITE_KEY_PAIR=bosh
```

I even tried hard-coding my access key and secret in `templates/vagrant-aws.tpl` but I got the same error. Is it possible my access key has special characters that vagrant cannot accept?

**Comment by bosh-ci-push-pull** [comment]
Hi Rob,

Sometimes when you have multiple providers in the Vagrantfile you encounter
this error. Maybe you can try having one provider and see if that will fix
the issue.

Here's a link to someone with a similar problem:
https://github.com/mitchellh/vagrant-aws/issues/290

Graeme & Thulasi



On Mon, Feb 16, 2015 at 2:50 PM, Rob Dimsdale <notifications@github.com>
wrote:

> I try to vagrant up --provider=aws and I get the following error
>
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
>
> AWS Provider:
> * An access key ID must be specified via "access_key_id"
> * A secret access key is required via "secret_access_key"
> * vagrant_aws.config.ami_required
>
> Output of env | grep -i bosh
>
> BOSH_LITE_SUBNET_ID=[redacted]
> BOSH_AWS_ACCESS_KEY_ID=[redacted]
> BOSH_LITE_NAME=Vagrant
> BOSH_LITE_PRIVATE_KEY=[redacted]
> BOSH_AWS_SECRET_ACCESS_KEY=[redacted]
> BOSH_LITE_SECURITY_GROUP=inception
> BOSH_LITE_KEY_PAIR=bosh
>
> I even tried hard-coding my access key and secret in
> templates/vagrant-aws.tpl but I got the same error. Is it possible my
> access key has special characters that vagrant cannot accept?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-lite/issues/235>.
>



-- 
Thulasi Nandakumaran
thulasi@pivotallabs.com

**Comment by robdimsdale** [comment]
Yes, it appears to be a known issue with vagrant 1.7. I reinstalled vagrant 1.6.3 (and 1.6.5) and that fixed this issue.

Thanks

**Comment by drnic** [comment]
Discovered this again when installing (latest) Vagrant on new machine. Downgrading again.

**Comment by drnic** [comment]
Why is the ticket closed?

**Comment by ahummel25** [comment]
So is there a particular access_key_id and secret_access_key that you need to provide in your dummy Vagrantfile for your aws box or can you put anything there?

**Comment by sergueif** [comment]
@drnic have you found a workaround for this? What versions of vagrant/vagrant-aws work on osx?

**Comment by drnic** [comment]
The workaround is downgrading to old vagrant 1.6.X
