### ISSUE TITLE
bosh-lite virtualbox VM crashes always on the second deploy

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/bosh-lite#240]
Hello, I can deploy cf-warden on the vagrant virtualboxVM.

After I edit something in the deployment manifest, I would like to run:
```
bosh deployment manifest.yml
bosh deploy
```
to update the deployment without destroy everything and restart from the beginning.

And after some time I get: 
```
Properties
ssl
  ± skip_cert_verify:
    - false
    + true

Meta
No changes

Please review all changes carefully

Deploying
---------
Deployment name: `cf.yml'
Director name: `Bosh Lite Director'
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 13
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started preparing dns > Binding DNS. Done (00:00:00)

  Started preparing configuration > Binding configuration. Done (00:00:02)

  Started updating job api_z1 > api_z1/0 (canary). Done (00:01:04)
  Started updating job hm9000_z1 > hm9000_z1/0 (canary). Done (00:01:37)
  Started updating job loggregator_z1 > loggregator_z1/0 (canary)[WARNING] cannot access director, trying 4 more times...
System call error while talking to director: No route to host - connect(2) (https://192.168.50.4:25555)
```
At this point I have to restart the VM on Virtualbox.

 If I run
```
bosh delete deployment cf-warden
bosh deploy
```
It works, but its really time expensive.
 If you need any logs, just tell me where to find them

**Comment by cppforlife** [comment]
We believe it has to do with the kernel version and loggregator usage. We will be releasing newer version of bosh-lite soon. Meanwhile you can you try updatign kernel on the VM by running `apt-get install utopic-lts-kernel` and rebooting.

**Comment by tyyko** [comment]
Hello, as your command was not working, I used  
```
sudo  apt-get install utopic-lts-kernel
[rebooted] 
```
Now any deploy of cf have no network connection, not even a logsearch deployment that always worked.

With no connection I mean: 
cf api 
Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: dial tcp 10.244.0.34:443: i/o timeout

ping 10.244.0.34
PING 10.244.0.34 (10.244.0.34) 56(84) bytes of data.
From 10.55.132.1 icmp_seq=1 Destination Host Unreachable

Kibana web interface of logsearch unreachable from the brosware


Please help
