### ISSUE TITLE
Bosh upload release Error 30002: Extracting release archive failed.

### ISSUE THREAD

**Issue by jgasmi** [cloudfoundry/bosh-lite#245]
I tried to install bosh-lite on mac os yosemite and I got the below problem, I have re-installed every thing on ubuntu and I got the same error !! 

Any help please ?
 
Uploading release
[WARNING] cannot access director, trying 4 more times...24.7MB/s ETA:  00:02:31
release.tgz:   100% |oooooooooooooooooooooooo|   5.1GB  18.2MB/s Time: 00:04:47

Director task 3
  Started extracting release > Extracting release. Failed: Extracting release archive failed. Check task debug log for details. (00:00:00)

Error 30002: Extracting release archive failed. Check task debug log for details.

Task 3 error

For a more detailed error report, run: bosh task 3 --debug

Director task 3
I, [2015-03-23T06:07:38.314370 #1377] [0x3f9e33771328]  INFO -- TaskHelper: Director Version: 1.2811.0
I, [2015-03-23T06:07:38.314469 #1377] [0x3f9e33771328]  INFO -- TaskHelper: Enqueuing task: 3
I, [2015-03-23 06:07:41 #4109] []  INFO -- DirectorJobRunner: Looking for task with task id 3
D, [2015-03-23 06:07:41 #4109] [] DEBUG -- DirectorJobRunner: (0.000997s) SELECT * FROM "tasks" WHERE "id" = 3
I, [2015-03-23 06:07:41 #4109] []  INFO -- DirectorJobRunner: Starting task: 3
I, [2015-03-23 06:07:41 #4109] [task:3]  INFO -- DirectorJobRunner: Creating job
D, [2015-03-23 06:07:41 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000559s) SELECT * FROM "tasks" WHERE "id" = 3
I, [2015-03-23 06:07:41 #4109] [task:3]  INFO -- DirectorJobRunner: Performing task: 3
D, [2015-03-23 06:07:41 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000393s) BEGIN
D, [2015-03-23 06:07:41 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000544s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2015-03-23 06:07:41.333187+0000', "description" = 'create release', "result" = NULL, "output" = '/var/vcap/store/director/tasks/3', "checkpoint_time" = '2015-03-23 06:07:41.333300+0000', "type" = 'update_release', "username" = 'admin' WHERE ("id" = 3)
D, [2015-03-23 06:07:41 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000896s) COMMIT
I, [2015-03-23 06:07:41 #4109] [task:3]  INFO -- DirectorJobRunner: Processing update release
I, [2015-03-23 06:07:41 #4109] [task:3]  INFO -- DirectorJobRunner: Extracting release
E, [2015-03-23 06:07:41 #4109] [task:3] ERROR -- DirectorJobRunner: Failed to extract release archive '/var/vcap/data/tmp/director/0000000009' into dir '/var/vcap/data/tmp/director/d20150323-4109-15rjd52', tar returned 2, output: 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

E, [2015-03-23 06:07:42 #4109] [task:3] ERROR -- DirectorJobRunner: Extracting release archive failed. Check task debug log for details.
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/update_release.rb:88:in `extract_release'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/update_release.rb:53:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/base_job.rb:54:in `block in single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/base_job.rb:48:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/event_log.rb:50:in `track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/base_job.rb:46:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/base_job.rb:54:in `single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/update_release.rb:53:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/job_runner.rb:108:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/job_runner.rb:31:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.2811.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/job_runner.rb:31:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2811.0/bin/bosh-director-worker:83:in `<top (required)>'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `load'
/var/vcap/packages/director/bin/bosh-director-worker:16:in `<main>'
D, [2015-03-23 06:07:42 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000455s) BEGIN
D, [2015-03-23 06:07:42 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000501s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2015-03-23 06:07:42.090316+0000', "description" = 'create release', "result" = 'Extracting release archive failed. Check task debug log for details.', "output" = '/var/vcap/store/director/tasks/3', "checkpoint_time" = '2015-03-23 06:07:41.333300+0000', "type" = 'update_release', "username" = 'admin' WHERE ("id" = 3)
D, [2015-03-23 06:07:42 #4109] [task:3] DEBUG -- DirectorJobRunner: (0.000897s) COMMIT
I, [2015-03-23 06:07:42 #4109] []  INFO -- DirectorJobRunner: Task took 0.76234298 seconds to process.

Task 3 error

**Comment by hsiliev** [comment]
The same error appears on my Mac (Yosemite). The Director error.log contains:
```
2015/03/23 08:38:54 [error] 1768#0: *848 client intended to send too large body: 5469673181 bytes, client: 192.168.50.1, server: , request: "POST /releases HTTP/1.1", host: "192.168.50.4:25555"
```

The release upload fails on 1.7 to max 2GB every time.

The update to bosh_cli 1.2830.0 did not help.

**Comment by hsiliev** [comment]
Setting `client_max_body_size 8192m;` in `/var/vcap/jobs/director/config/nginx.conf` solves the problem.

cf-release is now definitely bigger than 5GB.

**Comment by jgasmi** [comment]
it solved my problem too, really thank you for your help.

**Comment by bosh-ci-push-pull** [comment]
Please see
https://groups.google.com/a/cloudfoundry.org/forum/#!topic/bosh-users/MjiFAdpyimQ

**Comment by ezhang-pivotal** [comment]
It's still error when using 205

**Comment by acca** [comment]
Solved setting `client_max_body_size` to `8192` and using 205 with BOSH and MicroBOSH. We restarted the director VM (perhaps it work restarting just nginx). Thanks

**Comment by waltervalenti** [comment]
Bosh on Openstack.
I've got  the same problem, but I can't modify /var/vcap/jobs/director/config/nginx.conf.
I'm logged in (with ssh key) , like vcap and the change requires "root".
I can't make "sudo", because requires the password.

**Comment by acca** [comment]
Try to grant root with sudo su, using this password: c1oudc0w

**Comment by waltervalenti** [comment]
>________________________________
> Da: acca <notifications@github.com>
>A: cloudfoundry/bosh-lite <bosh-lite@noreply.github.com> 
>Cc: waltervalenti <waltervalenti@yahoo.it> 
>Inviato: Martedì 14 Aprile 2015 16:24
>Oggetto: Re: [bosh-lite] Bosh upload release Error 30002: Extracting release archive failed. (#245)
> 
>
>
>Try to grant root with sudo su, using this password: c1oudc0w
>—


It works.
Thanks.

Walter
