### ISSUE TITLE
deploy-cf.md misses 'update' step

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/bosh-lite#246]
I have been following the instructions on deploy-cf.md for a manual deploy. I got to the part where you run make_manifest_spiff, and it bailed on a missing cf-lamb file.

It turns out src/loggregator was an empty directory.

I think this would have been resolved if there had been a previous step to run the update script after cloning cf-release?

**Comment by chrisumbel** [comment]
I had the same issue and the 'update' script worked for me. I don't *think* this was necessary in early March, but certainly seems so now.

**Comment by cppforlife** [comment]
Fixed.
