### ISSUE TITLE
Instructions in BuildBoxes.md no longer work

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-lite#247]
Commit https://github.com/cloudfoundry/bosh-lite/commit/7b91e0a2b3a16d022adaac74cf86bf401faa711a introduced file resources that are not setup by the `bin/build-{virtualbox,vmware}` scripts but only in a the ci pipeline. That change breaks the `bin/build-{vmware,virtualbox}` scripts that are referenced in `BuildBoxes.md`.

```
)$ ./bin/build-vmware 54 18 9000.16.0
vmware-iso output will be in this color.

1 error(s) occurred:

* Bad source 'bosh-release.tgz': stat bosh-release.tgz: no such file or directory
```

**Comment by cppforlife** [comment]
Updated.
