### ISSUE TITLE
Running BOSH Agent in container: dial tcp 127.0.0.1:7777: i/o timeout

### ISSUE THREAD

**Issue by krishna-mk** [cloudfoundry/bosh-lite#248]
Similar to the issue:
Running errand fails to refill resource pool due to i/o timeout #219
robdimsdale opened this issue on Dec 6, 2014 · 2 comments - closed

I am getting the similar issues in my bosh-lite setup. 
After installing the cf-release and cf-mysql-release, while installing the notification-release this is the error showing up. 
bosh task debug shows the similar log pasted by robdimsdale in previous issue.

   Failed refilling resource pools > default/0: Creating VM with agent ID 'b4f1d57c-5d44-40d6-83af-8b39dc21de54': Running BOSH Agent in container: dial tcp 127.0.0.1:7777: i/o timeout (00:00:02)
   Failed refilling resource pools (00:00:02)

Error 100: Creating VM with agent ID 'b4f1d57c-5d44-40d6-83af-8b39dc21de54': Running BOSH Agent in container: dial tcp 127.0.0.1:7777: i/o timeout

**Comment by cppforlife** [comment]
Havent seen this problem for a long time. Closing.
