### ISSUE TITLE
tcpdump no longer available

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry/bosh-lite#256]
Used to work inside the warden containers

```
tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied
```

**Comment by cppforlife** [comment]
which version of warden stemcell are you using? we have not published any new warden stemcells in a long time.

**Comment by fhanik** [comment]
it's been a while since I actually tried to use tcpdump, so I can't tell when it changed. I just reprovisioned my system using bin/provision_cf which would pick up the latest

**Comment by fhanik** [comment]
Full trace to show the permission denied problems

    strace tcpdump
    execve("/usr/sbin/tcpdump", ["tcpdump"], [/* 17 vars */]) = 0
    brk(0)                                  = 0x7f5c99897000
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5c988a0000
    access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
    open("/lib/x86_64-linux-gnu/tls/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/x86_64-linux-gnu/tls/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/tls/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/x86_64-linux-gnu/tls", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/x86_64-linux-gnu/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/lib/x86_64-linux-gnu/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
    stat("/lib/x86_64-linux-gnu", 0x7fff42f08360) = -1 EACCES (Permission denied)
    open("/usr/lib/x86_64-linux-gnu/tls/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/x86_64-linux-gnu/tls/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/usr/lib/x86_64-linux-gnu/tls/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/x86_64-linux-gnu/tls", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/usr/lib/x86_64-linux-gnu/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/x86_64-linux-gnu/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/x86_64-linux-gnu", 0x7fff42f08360) = -1 EACCES (Permission denied)
    open("/lib/tls/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/tls/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/lib/tls/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/tls", 0x7fff42f08360)        = -1 ENOENT (No such file or directory)
    open("/lib/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib/x86_64", 0x7fff42f08360)     = -1 ENOENT (No such file or directory)
    open("/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/lib", 0x7fff42f08360)            = -1 EACCES (Permission denied)
    open("/usr/lib/tls/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/tls/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/usr/lib/tls/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/tls", 0x7fff42f08360)    = -1 ENOENT (No such file or directory)
    open("/usr/lib/x86_64/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib/x86_64", 0x7fff42f08360) = -1 ENOENT (No such file or directory)
    open("/usr/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    stat("/usr/lib", 0x7fff42f08360)        = -1 EACCES (Permission denied)
    writev(2, [{"tcpdump", 7}, {": ", 2}, {"error while loading shared libra"..., 36}, {": ", 2}, {"libcrypto.so.1.0.0", 18}, {": ", 2}, {"cannot open shared object file", 30}, {": ", 2}, {"Permission denied", 17}, {"\n", 1}], 10tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied
    ) = 117

**Comment by fhanik** [comment]
I added a simple test case to the warden spec files to test it directly there. 
tcpdump works in a container there, so it seems more likely that is part of bosh-lite

**Comment by fhanik** [comment]
Workaround for now is to use ngrep

**Comment by cppforlife** [comment]
@fhanik I've tried it on aws VM (outside of containers):

```
ubuntu@agent-id-bosh-0:~$ sudo tcpdump -lni eth0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
^C
0 packets captured
7 packets received by filter
0 packets dropped by kernel
```

I did have to sudo of course. Will try inside a container...

**Comment by dpb587-pivotal** [comment]
Closing in favor of cloudfoundry/bosh#1654 since it's more central and would probably be a stemcell-level change.
