### ISSUE TITLE
Permission Issue with the Bundled Cloud Foundry: Can't Create Service Instances

### ISSUE THREAD

**Issue by mhlandry** [cloudfoundry/bosh-lite#258]
I'm trying to get the introduction to spring cloud
<https://spring.io/blog/2014/06/03/introducing-spring-cloud> app working
with an instance of Cloud Foundry that I'm running on my machine. I tried
to push the app and I get this message:

        Could not find service postgres-service to bind to hello-spring-cloud

That makes sense to me so I started tracking down the postgres service.
When I run `cf marketplace`, I get:

        service      plans     description
        mongodb      default   MongoDB NoSQL database
        postgresql   default   PostgreSQL database
        rabbitmq     default   RabbitMQ message queue
        redis        default   Redis key-value store

When I try to create a service instance of the postgresql service and I
get:

        $ cf create-service postgresql default postgresql-service
        Creating service instance postgresql-service in org xyz / space development as admin...
        FAILED
        Server error, status code: 500, error code: 10001, message: Service broker error: Not authorized

Here are the permissions for the space:

        Getting users in org xyz / space development as admin

        SPACE MANAGER
        admin

        SPACE DEVELOPER
        Admin

The cf service-access command doesn't yield anything interesting:

        $ cf service-access
        Getting service access as admin

Then it shows nothing on the terminal. So I tried to enable service access

        $ cf enable-service-access postgresql
        Enabling access to all plans of service postgresql for all orgs as admin...
        All plans of the service are already accessible for all orgs
        OK

For the life of me, I can¹t figure out what's going on.  Any ideas about what's going on?

**Comment by cppforlife** [comment]
@shalako any ideas?

**Comment by shalako** [comment]
I'm guessing that you are using the [legacy community services](https://github.com/cloudfoundry-community/cf-services-contrib-release). These use the [deprecated v1 broker API](http://docs.cloudfoundry.org/services/api-v1.html). If this is true, I recommend asking the maintainers of that repo for help.

Many new features in CF are not designed to support v1 brokers. This is why I expect you get no results for the `service-access` command.

[Registration of v1 brokers is a two-step process](http://docs.cloudfoundry.org/services/api-v1.html#authentication). 
1. Give your brokers cc admin credentials or enable it to obtain a token with admin permissions. This enables a v1 broker to automatically publish its catalog to CF. This appears to be working, as the services show up in the marketplace.
2. Register a service-auth-token **for each service** with CF. This enables CF to make API calls to v1 brokers for create/bind/unbind/delete.

I'm guessing you've done step 1, but not step 2.

**Comment by mhlandry** [comment]
@shalako Thanks for the response!  I think you are dead on.  Please pardon my ignorance on the issue as I am very new to these frameworks.

I definitely did use the legacy community services, but I also notice when I do `curl https://api.10.244.0.34.xip.io/v2/services` I see those four services mentioned in my previous post.  Does that mean I have the Version 2 Services as well?

At any rate, my goal is simply to get a PostgreSQL service broker up and running in Cloud Foundry.  I've done a lot of googling and this does not seem to be a simple problem.  Can you point me in the right direction?

**Comment by shalako** [comment]
Hello Matthew,

I am not aware of another BOSH deployable PostgreSQL Service for CF, so if that if that is a requirement do what works. 

If MySQL is an option, there is a v2 bosh deployed MySQL service that is actively maintained: github.com/cloudfoundry/cf-mysql-release. 

The endpoint you're curling is the CloudFoundry public API (served by a component called Cloud Controller. The broker API is a separate integration for which cloud controller is the client (it is confusing that v1 brokers are also clients of the v2 CF API; that integration was bi-directional and has been simplified for the v2 broker API).  For more info, see docs.cloudfoundry.org/services. 

Best,
Shannon
