### ISSUE TITLE
[aws] Change ownership of some files

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-lite#259]
On a new bosh-lite on AWS the following files are owned by `root` instead of `ubuntu` user:

* `/home/ubuntu/.bosh_config`
* `/home/ubuntu/tmp` directory

Can we change their ownership to `ubuntu` before finishing the image creation?

**Comment by cppforlife** [comment]
Done as of 9000.31.0.

**Comment by drnic** [comment]
Thanks

On Tue, May 19, 2015 at 4:43 PM, Dmitriy Kalinin <notifications@github.com>
wrote:

> Closed #259 <https://github.com/cloudfoundry/bosh-lite/issues/259>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-lite/issues/259#event-309022743>.
>



-- 
Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic
