### ISSUE TITLE
Add pipeline.yml into ci folder

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-lite#261]
Sorry if I'm blind and just can't see it - but if its missing, can you add in your pipeline.yml for http://lite.bosh-ci.cf-app.com:8080/ please?

I'm trying to document all the public concourses & their pipeline.yml as examples for ppl to learn from.

**Comment by cppforlife** [comment]
Will do.

**Comment by cppforlife** [comment]
On master.
