### ISSUE TITLE
cf v209 manifest missing an attribute - deployment fails

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry/bosh-lite#265]
Using spiff to create the manifest for a cf deployment to bosh-lite results in a manifest that is missing the metron_agent.deployment property. https://gist.github.com/cdavisafc/f1358908042f31af647a

Adding that property to all job properties (where the metron tag exists) and into the properties section fixes the problem

**Comment by cppforlife** [comment]
How are you generating this manifests? Are you using bin/provision_cf? CI build that uses bin/provision_cf has been green and successfully provisions cf [1].

[1] http://lite.bosh-ci.cf-app.com:8080/jobs/deploy-cf-aws/builds/38

**Comment by mjseid** [comment]
I don't think this is bosh-lite specific.....
I see the same thing on v210 when issuing the following command in the cf-release directory
./generate_deployment_manifest vsphere cf_my_stub.yml > cf_210.yml

**Comment by Amit-PivotalLabs** [comment]
@cdavisafc This is not a bosh-lite issue, this is just an incongruence between the latest cf manifest generation templates and whatever stubs you're using.  What command did you run exactly to generate the manifest?  What SHA of cf-release were you working against?

**Comment by cppforlife** [comment]
Opened cf-release issue instead; closing here.

**Comment by gberche-orange** [comment]
@cdavisafc is it possible that you were missing a ``git submodule update`` on cf-release repo, which would have left cf-release/templates/cf-lamb.yml out of date (as it actually resides into loggregator submodule) ?
