### ISSUE TITLE
Cannot `bosh ssh` anymore to warden VMs

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-lite#288]
We booted up a new bosh-lite on AWS today and now from inside the VM we cannot `bosh ssh` into jobs/warden containers:

```
$ bosh ssh
Acting as user 'admin' on deployment 'try-anything-stannis' on 'Bosh Lite Director'
...

Starting interactive shell on job agent/0
No ECDSA host key is known for 10.244.25.6 and you have requested strict checking.
Host key verification failed.
```

Workaround?

I've tried disabling everything I can think of in `~/.ssh/config`:

```
Host *
  StrictHostKeyChecking=no
  UserKnownHostsFile=/dev/null
  NoHostAuthenticationForLocalhost yes
```

**Comment by bosh-ci-push-pull** [comment]
Ah. New option on bosh ssh --strict_host_key_checking no. Does that work
for you?

**Comment by geofffranks** [comment]
That works. What changed? Any chance we can have this be specified in the bosh config for a specific target, so strict-host-key-checking is on for prod, but off for bosh-lite?

**Comment by cppforlife** [comment]
We made bosh ssh too strict too early. We have two stories (https://www.pivotaltracker.com/story/show/102530088, ...) going through the pipeline to remedy this situation.

**Comment by xacaxulu** [comment]
+1
Adding `--strict_host_key_checking no` to the bosh ssh command worked.

**Comment by cppforlife** [comment]
Closing. Flag is no longer necessary with updated bosh-lite stemcells.
