### ISSUE TITLE
New warden cpi uses garden

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh-lite#289]
bosh_lite_manifest_template.yml need to be updated to use garden instead of warden

**Comment by cppforlife** [comment]
It's already done on develop (https://github.com/cloudfoundry/bosh-lite/commit/c3e97dc4dc3f46fe656f53c8bee14a0324dc0eb5#diff-5736f6304208b0d5bf03aebcc96cb21fR40); however, I've run into a problem running warden inside garden. Garden team will investigate.

**Comment by cppforlife** [comment]
On master.

**Comment by longnguyen11288** [comment]
new image is still using warden? also is there any advantages of using garden? hopefully better stability?
