### ISSUE TITLE
Add ami_regions to packer templates for aws

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh-lite#290]
adding ami_regions to aws packer json can copy ami to all the other regions. Having bosh-lite in all other regions would be amazing! Do you guys mind doing this? I can make PR for it if so

**Comment by cppforlife** [comment]
Do you know if packer's vagrant post processor deals properly with multiple AMIs?

**Comment by longnguyen11288** [comment]
I can confirm that vagrant puts all the region's ami into vagrant file

**Comment by longnguyen11288** [comment]
I ran it myself

**Comment by longnguyen11288** [comment]
https://github.com/cloudfoundry/bosh-lite/pull/292 done here

**Comment by longnguyen11288** [comment]
merged in PR

**Comment by cppforlife** [comment]
In 9000.54.0+.

**Comment by drnic** [comment]
xoxo thanks!
