### ISSUE TITLE
Connection timeout on bosh ssh

### ISSUE THREAD

**Issue by Koizumi85** [cloudfoundry/bosh-lite#296]
Hello together,

today I used bosh-lite the first time and I can't ssh into my containers.
I called "templates/add-route" and the route seems to be added.
I deployed the cf-haproxy-boshrelease and everything seems to be fine with the deployment.
Both containers are started and have status "running" when I run "bosh vms".
But if I try to run "bosh ssh" and then choose one of the jobs, the shell hangs on "Starting interactive shell on job public_haproxy_z1/0" and after a minute it tells "ssh: connect to host 10.244.50.2 port 22: Connection timed out"
Does anyone have an idea what could cause this problem?

**Comment by cppforlife** [comment]
Sounds like 10.244.50.2 is not a good IP. what's the output of `bosh vms`?

**Comment by Koizumi85** [comment]
@cppforlife 
Output of bosh vms is:

| private_haproxy_z1/0 | running | small_z1      | 10.244.50.14 |
| public_haproxy_z1/0  | running | small_z1      | 10.244.50.2  |

Complete Output of the bosh ssh command is:

```
christian@christian-ThinkPad-L530:~/dev/repos/bosh-lite$ bosh ssh
1. public_haproxy_z1/0
2. private_haproxy_z1/0
Choose an instance: 1
Acting as user 'admin' on deployment 'cf-haproxy-warden' on 'Bosh Lite Director'
Enter password (use it to sudo on remote host): *****
Target deployment is `cf-haproxy-warden'

Setting up ssh artifacts

Director task 9

Task 9 done
Starting interactive shell on job public_haproxy_z1/0
ssh: connect to host 10.244.50.2 port 22: Connection timed out

Cleaning up ssh artifacts

Director task 10

Task 10 done
```

**Comment by bosh-ci-push-pull** [comment]
Let's do a sanity check:

vagrant ssh
ssh vcap@10.244.50.2

Does that work?

**Comment by Koizumi85** [comment]
Yes, this works.

**Comment by bosh-ci-push-pull** [comment]
Sounds like then add-route did not work for you. Please confirm that proper
route is in the route table.

**Comment by Koizumi85** [comment]
Output of `route` command:

```
Ziel            Router          Genmask         Flags Metric Ref    Use Iface
default         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
10.244.0.0      192.168.50.4    255.255.224.0   UG    0      0        0 vboxnet0
192.168.1.0     *               255.255.255.0   U     1      0        0 eth0
192.168.50.0    *               255.255.255.0   U     0      0        0 vboxnet0
```

**Comment by cppforlife** [comment]
```
$ ipcalc 10.244.0.0/19
Address:   10.244.0.0           00001010.11110100.000 00000.00000000
Netmask:   255.255.224.0 = 19   11111111.11111111.111 00000.00000000
Wildcard:  0.0.31.255           00000000.00000000.000 11111.11111111
=>
Network:   10.244.0.0/19        00001010.11110100.000 00000.00000000
HostMin:   10.244.0.1           00001010.11110100.000 00000.00000001
HostMax:   10.244.31.254        00001010.11110100.000 11111.11111110
Broadcast: 10.244.31.255        00001010.11110100.000 11111.11111111
Hosts/Net: 8190                  Class A, Private Internet
```

Note that IP you have chosen falls outside of 10.244.0.1-10.244.31.254 range. You can change add-route to forward /16 to gw IP which should fix your problem.

**Comment by cppforlife** [comment]
Fixed in https://github.com/cloudfoundry/bosh-lite/commit/1e82360f0bd00f75a367ddea81a024aebf514a74
