### ISSUE TITLE
provision_cf script doesn't work with latest version of cf-release

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-lite#300]
It looks like current bosh-lite from `master` branch does not supports working with the latest v218 cf-release.

The problem is that `update` scripts were moved from root directory to `scripts` folder by this commit https://github.com/cloudfoundry/cf-release/commit/2a83461b450ba6e9cd555c4f2048c91a40507bcc. And the [current version](https://github.com/cloudfoundry/bosh-lite/blob/8b4a470846d90692b5e5711e45073714ff39f1ee/bin/provision_cf#L32) of `provision_cf` script does not takes into account this changes.

**Comment by allomov** [comment]
I believe that this PR https://github.com/cloudfoundry/bosh-lite/pull/293 can cope with this issue. Can't get why this changes are not merged yet. New-comers suffer because of this issue.

**Comment by cppforlife** [comment]
Pulled in changes from mega team: https://github.com/cloudfoundry/bosh-lite/pull/299. Closing this one in favor of #299.

**Comment by allomov** [comment]
Great. Thank you very much.
