### ISSUE TITLE
Setting api endpoint to https://api.10.244.0.34.xip.io fails.

### ISSUE THREAD

**Issue by bnanda** [cloudfoundry/bosh-lite#302]
I am very new to CloudFoundry and I am having the following problem with cf-release 219.

After successfully following all steps in README, I am able to deploy CloudFoundry using VirtualBox on my MacBook. The "provision_cf" command passes without any problem and cloudcheck does not show any errors. Then I issue the "add-route" command to add a route.

However, after adding the route, when I try to set the API end point as followed, I see the following error:

bnanda-mac:bosh-lite bnanda$ cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
Setting api endpoint to https://api.10.244.0.34.xip.io...
FAILED
Server error, status code: 404, error code: 0, message:

I have tried everything, i.e. removing the bosh-lite virtual machine, re-provisioning the CF, however every time, I am stuck at this step.

Earlier, I could do this with cf-release 218. The problem started happening after upgrading to cf-release 219. I am running out of ideas now. Please help.

**Comment by bnanda** [comment]
Environment Details:
=================================================================
bnanda-mac:bosh-lite bnanda$ uname -a
Darwin bnanda-mac.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

bnanda-mac:bosh-lite bnanda$ vagrant -v
Vagrant 1.7.4

bnanda-mac:bosh-lite bnanda$ bosh version
BOSH 1.3093.0

bnanda-mac:bosh-lite bnanda$ cf -v
cf version 6.12.4-b4b6af1-2015-09-18T17:54:54+00:00

bnanda-mac:bosh-lite bnanda$ bosh releases
Acting as user 'admin' on 'Bosh Lite Director'

+------+----------+-------------+
| Name | Versions | Commit Hash |
+------+----------+-------------+
| cf   | 219*     | 0e63f392+   |
+------+----------+-------------+
(*) Currently deployed
(+) Uncommitted changes

Releases total: 1

bnanda-mac:bosh-lite bnanda$ bosh deployments
Acting as user 'admin' on 'Bosh Lite Director'

+-----------+------------+-------------------------------------------------+--------------+
| Name      | Release(s) | Stemcell(s)                                     | Cloud Config |
+-----------+------------+-------------------------------------------------+--------------+
| cf-warden | cf/219     | bosh-warden-boshlite-ubuntu-trusty-go_agent/389 | none         |
+-----------+------------+-------------------------------------------------+--------------+

Deployments total: 1

bnanda-mac:bosh-lite bnanda$ bosh status
Config
             /Users/bnanda/.bosh_config

Director
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.3074.0 (00000000)
  User       admin
  UUID       9bca5701-66c0-43ee-a4d0-64813b4b5ece
  CPI        cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

Deployment
  Manifest   /Users/bnanda/CFWorkspace/cf-release/bosh-lite/deployments/cf.yml
  
bnanda-mac:bosh-lite bnanda$ bosh cck
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Performing cloud check...

Director task 5
  Started scanning 12 vms
  Started scanning 12 vms > Checking VM states. Done (00:00:00)
  Started scanning 12 vms > 12 OK, 0 unresponsive, 0 missing, 0 unbound, 0 out of sync. Done (00:00:00)
     Done scanning 12 vms (00:00:00)

  Started scanning 4 persistent disks
  Started scanning 4 persistent disks > Looking for inactive disks. Done (00:00:01)
  Started scanning 4 persistent disks > 4 OK, 0 missing, 0 inactive, 0 mount-info mismatch. Done (00:00:00)
     Done scanning 4 persistent disks (00:00:01)

Task 5 done

Started		2015-10-03 00:46:29 UTC
Finished	2015-10-03 00:46:30 UTC
Duration	00:00:01

Scan is complete, checking if any problems found...
No problems found

bnanda-mac:bosh-lite bnanda$ bosh ssh
1. consul_z1/0
2. ha_proxy_z1/0
3. nats_z1/0
4. etcd_z1/0
5. postgres_z1/0
6. uaa_z1/0
7. api_z1/0
8. hm9000_z1/0
9. runner_z1/0
10. doppler_z1/0
11. loggregator_trafficcontroller_z1/0
12. router_z1/0
13. acceptance_tests/0
14. smoke_tests/0

**Comment by ematpl** [comment]
Hi, @bnanda,

Version 219 of cf-release is the first final release of CF to include commit https://github.com/cloudfoundry/cf-release/commit/1c9f091b1407b63f337fe1f7b3b438dfcaf6c7ac, which changes the default domain for BOSH-lite deployments from `10.244.0.34.xip.io` to `bosh-lite.com` (which, like `10.244.0.34.xip.io`, resolves itself and its subdomains to the IP address 10.244.0.34). Can you try those instructions with `cf api --skip-ssl-validation api.bosh-lite.com` instead?

Thanks,
Eric

**Comment by bnanda** [comment]
Hi Eric,

Thanks for your help. I followed your suggestions and resolved my problem.

Thanks,
Biswajit
