### ISSUE TITLE
provision_cf fails on spiff error

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/bosh-lite#307]
Using latest cf-release and bosh-lite on master today (17th), failed to launch cf on bosh-lite using provision_cf script:

    2015/010/17 21:22:38 error generating manifest: unresolved nodes:
        dynaml.MergeExpr{[properties <<]}

I have rolled back to cf-release 217 and bosh-lite 9000.55.0 and can proceed.

**Comment by johnmcteague** [comment]
In actual fact I continue to get an error with these versions also:

```
 export CF_RELEASE_DIR=/code/cf-release
+ CF_RELEASE_DIR=/code/cf-release
+ ./bin/make_manifest_spiff
737bd8ee-f4f9-4aec-9b82-80f3d0be26f1
WARNING: The './generate_deployment_manifest' file is deprecated and will be removed. Please use './scripts/generate_deployment_manifest' instead.
2015/10/17 22:28:17 error generating manifest: unresolved nodes:
	dynaml.MergeExpr{[properties <<]}
Incorrect YAML structure in `/code/bosh-lite/manifests/cf-manifest.yml': expected Hash at the root
```

**Comment by cppforlife** [comment]
Moved to cf-release: https://github.com/cloudfoundry/cf-release/issues/818
