### ISSUE TITLE
Setting API endpoint fails in CF CLI on bosh-lite setup

### ISSUE THREAD

**Issue by raphaelvannson** [cloudfoundry/bosh-lite#309]
# Message
Hello, can you advise on the following issue occurring when attempting to target the CF API deployed on bosh-lite?<br> I have attempted to resolve this myself via reading of documentation, mailing lists, forums but am out of magic tricks.<br>
Let me know if you need additional information.

Thanks,
Raphael

# System details

Virtual Box 4.3.28

```
$ uname -a
Darwin MUSRV186016-382 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

$ vagrant -v
Vagrant 1.7.2

$ bosh -v
BOSH 1.3088.0

$ cf -v
cf version 6.13.0-e68ce0f-2015-10-15T22:53:29+00:00

$ whereis spiff
/usr/bin/spiff
```

The laptop host is not behind a proxy.

# How the error was produced
## Pre-requisites
__Strictly__ followed instructions to:
 
* [Setup bosh-lite](https://github.com/cloudfoundry/bosh-lite) -- (btw: ```./bin/provision_cf``` failed with a ```...bosh/cf-release: No such file or directory``` after uploading the stemcell but that is not the topic of this issue).
* [Deploy cloud foundry release to bosh-lite](http://docs.cloudfoundry.org/deploying/boshlite/) (see status of VMs after ```bosh deploy``` below).
* [Install the CF CLI](https://github.com/cloudfoundry/cli)

```
$ bosh vms
Acting as user 'admin' on 'Bosh Lite Director'
Deployment `cf-warden'

Director task 39

Task 39 done

+------------------------------------+---------+---------------+--------------+
| Job/index                          | State   | Resource Pool | IPs          |
+------------------------------------+---------+---------------+--------------+
| api_z1/0                           | running | large_z1      | 10.244.0.134 |
| consul_z1/0                        | running | small_z1      | 10.244.0.54  |
| doppler_z1/0                       | running | medium_z1     | 10.244.0.142 |
| etcd_z1/0                          | running | medium_z1     | 10.244.0.42  |
| ha_proxy_z1/0                      | running | router_z1     | 10.244.0.34  |
| hm9000_z1/0                        | running | medium_z1     | 10.244.0.138 |
| loggregator_trafficcontroller_z1/0 | running | small_z1      | 10.244.0.146 |
| nats_z1/0                          | running | medium_z1     | 10.244.0.6   |
| postgres_z1/0                      | running | medium_z1     | 10.244.0.30  |
| router_z1/0                        | running | router_z1     | 10.244.0.22  |
| runner_z1/0                        | running | runner_z1     | 10.244.0.26  |
| uaa_z1/0                           | running | medium_z1     | 10.244.0.130 |
+------------------------------------+---------+---------------+--------------+

VMs total: 12
```

## Error: ```api.bosh-lite.com``` is not resolved

```
$ cf api --skip-ssl-validation https://api.bosh-lite.com 
Setting api endpoint to https://api.bosh-lite.com...
FAILED
Error performing request: Get https://api.bosh-lite.com/v2/info: dial tcp: lookup api.bosh-lite.com: no such host
```

### Access to ha_proxy VM > OK
```
$ telnet 10.244.0.34 443
Trying 10.244.0.34...
Connected to 10.244.0.34.
Escape character is '^]'.
Connection closed by foreign host.

$ telnet 10.244.0.34 80
Trying 10.244.0.34...
Connected to 10.244.0.34.
Escape character is '^]'.
Connection closed by foreign host.
```

### Access to api VM >  OK

```
$ telnet 10.244.0.134 443
Trying 10.244.0.134...
telnet: connect to address 10.244.0.134: Connection refused
telnet: Unable to connect to remote host

$ telnet 10.244.0.134 80
Trying 10.244.0.134...
Connected to 10.244.0.134.
Escape character is '^]'.
Connection closed by foreign host.
```

### Trying to point directly to the api VM > KO - Provides empty response

```
$ cf api --skip-ssl-validation http://10.244.0.134
Setting api endpoint to http://10.244.0.134...
FAILED
Error performing request: Get http://10.244.0.134/v2/info: EOF
```

**Comment by cppforlife** [comment]
Moved to cf-release as it's CF specific.

**Comment by raphaelvannson** [comment]
Hello,

Sorry for not getting back to you sooner on this.
I am moved to another piece of work and things have been quite busy but may resume this particular stream of work later.
I will get back to you with the information requested if that is the case. The issue can remain closed in the meantime.

Thanks,
Raph

**Comment by ChandraNarayanasamy** [comment]
Hi raphaelvannson

May I know if you are able to set the end point now and what changes did you do? We are also facing exact same issue you mentioned and did all the steps you mentioned about.

Thanks in advance.

**Comment by jtarchie** [comment]
@ChandraNarayanasamy if you follow the issue to cf-release, it notes that the most likely culprit is DNS resolution.

Look here for more [information](https://github.com/cloudfoundry/cf-release/issues/825).

**Comment by ChandraNarayanasamy** [comment]
Hi @jtarchie we followed all of them and we tried using google dns and open dns. But it is not working in either of the cases. We are behind the proxy and the proxy is being setup.

Thank you
Chandra
