### ISSUE TITLE
Network already acquired when trying to deploy a previously deleted deployment

### ISSUE THREAD

**Issue by williammartin** [cloudfoundry/bosh-lite#311]
On very recent bosh-lite installations, we are seeing strange behaviour related to network acquisition. Several times, when trying to deploy after previously deleting the deployment (with or without --force), we are seeing similar messages to the following:

`Error 100: Creating VM with agent ID 'cfd86507-0dec-417f-b19f-5d87806bf783': Creating container: network already acquired: 10.244.9.16/30`

To resolve this, I have been issuing a `vagrant reload` and then retrying the `bosh deploy`

I'm sorry I don't have more information on how to reliably recreate, if I discover something I will update.

**Comment by cppforlife** [comment]
"network already acquired: 10.244.9.16/30" error is shown when container with that IP is already present. Use of --force could definitely lead to this since the Director will continue even if it fails to clean up containers.

**Comment by williammartin** [comment]
Alright that's good to know. Would --force remove the container from `bosh vms` even if the deletion failed? I'm not sure if vms is intrinsically linked to deployments, i.e. 'I deleted that deployment so I won't look for any vms to show you'.

I'll try to do some more debug because I feel like we've seen this when doing a `bosh deploy` (using an unchanged manifest), on top of an existing deployment. Thanks!

**Comment by cppforlife** [comment]
> Would --force remove the container from bosh vms even if the deletion failed? 

yup, because from bosh's perspective it was deleted. expectation here that if operator is using --force, they will make sure to resolve any problems (deleting stuck vms) on the iaas side themselves.

**Comment by cppforlife** [comment]
Closing. Added to https://github.com/cloudfoundry/bosh-lite/blob/master/docs/troubleshooting.md#network-already-acquired.
