### ISSUE TITLE
garden-linux and new bosh-lite stemcell step over /etc/resolv.conf

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-lite#315]
When garden-linux spins up a container, it generates an `/etc/resolv.conf` by [copying][1] the host's `/etc/resolv.conf` into the container. This removes the symbolic link that was [preserved][2] by the stemcell builder and that ubuntu's `resolvconf` package relies on. The result is that `/etc/resolv.conf` looks like this when the container is first constructed:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 172.16.239.2
search localdomain
```

Later, when the consul agent starts in the container, it tests if the Ubuntu dynamic resolver is [enabled][3] and will either [update `/etc/resolv.conf` in place][4] or it will [regenerate][5] it.

In stemcell 2776, that would result in an `/etc/resolv.conf` that looks like this:

```
nameserver 127.0.0.1
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 172.16.239.2
search localdomain
```

Between stemcell 2776 and 3126, it looks like `/run/resolvconf/enable-updates` found its way into the warden stemcell. With that file present, the dynamic resolver is considered enabled in the bosh-lite containers so the consul agent control script regenerates resolv.conf into `/run/resolvconf/resolv.conf`. But, because of how garden sets things up, `/etc/resolv.conf` is no longer a symlink to `/run/resolvconf/resolv.conf` so `127.0.0.1` never gets added to the active dns server list. At this point we can resolve everything except what consul manages because we're stiill using what garden generated:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 172.16.239.2
search localdomain
```

If the symlink is fixed, the resolvconf tool starts managing `/etc/resolv.conf` on its own and loses what was propagated in by garden. Now we start to inherit stale data from the ec2 environment where the stemcell was built:

```
nameserver 127.0.0.1
nameserver 172.16.0.23
search ec2.internal
```

The ec2 DNS server isn't (usually) the correct DNS server so things are now completely broken.

If we want to go back to how they were with 2776, we need to explicitly disable `/etc/resolv.conf` updates by ubuntu by running `resolvconf --disable-updates` when building the warden stemcell or by deleting `/run/resolvconf/enable-updates`.

Even though the fix for this is likely to be in the bosh repository, I'm opening it here since it impacts bosh-lite.

[1]: https://github.com/cloudfoundry-incubator/garden-linux/blob/3165436b2d4e116b9da562dcfd0a8d111d2cf1c0/linux_backend/skeleton/setup.sh#L125-L142
[2]: https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/bosh_clean/apply.sh#L14-L30
[3]: https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/agent_ctl.sh.erb#L97
[4]: https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/agent_ctl.sh.erb#L100-L107
[5]: https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/agent_ctl.sh.erb#L98

**Comment by cppforlife** [comment]
Already on it: https://www.pivotaltracker.com/story/show/107958688.

Will make sure `resolvconf -u` works (enabled).

**Comment by cppforlife** [comment]
I believe warden stemcell 3147 addresses the issue.

cc @Amit-PivotalLabs
