### ISSUE TITLE
generate-bosh-lite-dev-manifest error

### ISSUE THREAD

**Issue by tintoverano** [cloudfoundry/bosh-lite#316]
hello Guys,

I'm a newbie and just made an aws deployment

I followed the docs to the very end with success where ./bin/provision_cf script is to be run

I'm getting the error below

````
CF Release has been updated
+ ./scripts/generate-bosh-lite-dev-manifest
/var/lib/gems/2.1.0/gems/bosh_cli-1.3144.0/bin/optionally_run_with_bundler.rb:22:in `write': Permission denied @ rb_sysopen - /var/lib/gems/2.1.0/gems/bosh_cli-1.3144.0/bin/run_bosh_with_bundler.Gemfile (Errno::EACCES)
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.3144.0/bin/optionally_run_with_bundler.rb:22:in `run'
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.3144.0/bin/bosh:3:in `<top (required)>'
	from /usr/local/bin/bosh:23:in `load'
	from /usr/local/bin/bosh:23:in `<main>'
Can only target Bosh Lite Director. Please use 'bosh target' before running this script.
```` 

$bosh status does tells that it is targeting Bosh Lite Director

could you help me with solving this issue?

thanks in advance

Zoltán

**Comment by cppforlife** [comment]
generate-bosh-lite-dev-manifest sets BOSH_USE_BUNDLER env variable which makes bosh cli run within bundler context. on some environment it wont work possibly because gems were installed with sudo. you can try removing that env variable from that script to make it work.

**Comment by tintoverano** [comment]
hi,

thanks, finally I went for bosh-bootstrap and reinstalled ruby using rvm.io and this time bundler worked fine

zoltán

**Comment by sjostric** [comment]
I solved this by using the gem mechanism to do a "user install". So, generic gems I install normally with sudo and bosh specific with option "--user-install", e.g.:

sudo gem install net-ssh -v 2.9.2
gem install bosh_cli --user-install
gem install bundler --user-install

(using Ubuntu 16.04)
