### ISSUE TITLE
Prevent Routing loops for unprovisioned 10.244.x.x VMs

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-lite#318]
If an end user creates a local route to send traffic to bosh-lite through vagrant using a large netmask, like 10.244.0.0/19, the configuration on bosh-lite + the warden CPI makes it very easy to accidentally DOS yourself with a routing loop, since any VM that attempts to talk to another that doesn't yet exist, will send its traffic out eth0 (default gateway), to the host networking, which then has a route for that IP back into vagrant. This would be fairly common when VMs come up before others during deploys, or if you have a service logging to a VM that does not yet exist from another deployment.

Could we get an iptables rule added to drop packets outbound from eth0 on the bosh-lite vagrant VM for any IPs in the warden network range? Not sure off the top of my head if that would be 10.244.0.0/16, or /19, or what.

**Comment by cppforlife** [comment]
Sounds reasonable. Would you be interested in making a PR?

**Comment by geofffranks** [comment]
This seems to work for me when creating vagrant images locally.
