### ISSUE TITLE
Dependencies not declared in README

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [cloudfoundry/bosh-lite#320]
We tried to deploy cloud foundry locally today and got hung up at a few places of configuration that weren't mentioned in the README. Feel free to close this issue if you think they're common enough dependencies that they don't need to be listed.

1: Bundler is required and not mentioned (we're on a pretty clean machine that only had the system ruby).

```
+ ./scripts/generate-bosh-lite-dev-manifest
~/.rbenv/versions/2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from ~/.rbenv/versions/2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel
```

2: The README mentions you can run the `./bin/provision_cf` script, but doesn't mention that you need to install spiff as mentioned by the `deploying Cloud Foundry documentation` linked.

```
+ ./scripts/generate-bosh-lite-dev-manifest
./scripts/../scripts/generate_deployment_manifest: line 27: spiff: command not found
Incorrect YAML structure in `/Users/pivotal/workspace/cf-release/bosh-lite/deployments/cf.yml': expected Hash at the root
```

3: At some point we got an error message relating to not having ruby version 2.1.7. We lost the terminal output of this one, but it could have been a red herring related to not having bundler. We've found success so far running the `./bin/provision_cf` after installing/using 2.1.7 with bundler.

Cheers, hope this is helpful.

**Comment by tomoe** [comment]
Hi @MarkyMarkMcDonald, 

I had the same problem as#2.
I made a pull request in "cf-release" project to improve the message to guide users to install spiff:
https://github.com/cloudfoundry/cf-release/pull/880

Let's see if that is accepted.

**Comment by cppforlife** [comment]
@MarkyMarkMcDonald @tomoe can we consider this issue resolved since cf-release merged the changes.

**Comment by tomoe** [comment]
@cppforlife The PR has been merged, so the item 2 is gone (or at least you'd get more friendly warning). 
I didn't get 1 or 3. So I'd leave it up to @MarkyMarkMcDonald .

**Comment by MarkyMarkMcDonald** [comment]
Spiff was the only one that actually took work, so sounds good to me. thanks!
