### ISSUE TITLE
cannot get ./scripts/generate-bosh-lite-dev-manifest running

### ISSUE THREAD

**Issue by NareshKosgi** [cloudfoundry/bosh-lite#322]
I'm trying to setup a local CF using bosh-lite.  Getting an issue when I run ./scripts/generate-bosh-lite-dev-manifest.  It states Director UUID is not defined in deployment manifest.  Did I miss a step here?

```
./scripts/generate-bosh-lite-dev-manifest deploy.yml
./scripts/generate-bosh-lite-dev-manifest: line 25: ./scripts/../bosh-lite/deployments/cf.yml: Permission denied
Director UUID is not defined in deployment manifest
```

**Comment by cppforlife** [comment]
@Amit-PivotalLabs any ideas?

**Comment by Amit-PivotalLabs** [comment]
@NareshKosgi @cppforlife migrated this issue to cf-release: https://github.com/cloudfoundry/cf-release/issues/864
