### ISSUE TITLE
::::----- Problem with the Vagrant Up Command on Ubuntu ----::::

### ISSUE THREAD

**Issue by MachineGamer** [cloudfoundry/bosh-lite#327]
Hey,
my problem is ,at first i just installed a ubuntu 15 64bit on the virtualbox program cause i am working on a school project anyway, i am following a lessons but i seem to stuck on the vagrant up command ,i've faced this problem twice at first then i've removed the tmp and tried the command again but the same issues this is the steps that i am following: 

machine-gamer@Gamer-VirtualBox:~$ ls
Desktop    Downloads         Music     Public     ud381
Documents  examples.desktop  Pictures  Templates  Videos
machine-gamer@Gamer-VirtualBox:~$ cd Documents
machine-gamer@Gamer-VirtualBox:~/Documents$ ls
Real-Time
machine-gamer@Gamer-VirtualBox:~/Documents$ cd Real-Time
machine-gamer@Gamer-VirtualBox:~/Documents/Real-Time$ ls
ud381
machine-gamer@Gamer-VirtualBox:~/Documents/Real-Time$ cd ud381/
machine-gamer@Gamer-VirtualBox:~/Documents/Real-Time/ud381$ ls
default.json  lesson2  lesson4       README.md    viz
lesson1       lesson3  provision.sh  Vagrantfile
machine-gamer@Gamer-VirtualBox:~/Documents/Real-Time/ud381$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'udacity/ud381' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'udacity/ud381'
    default: URL: https://atlas.hashicorp.com/udacity/ud381
==> default: Adding box 'udacity/ud381' (v0.0.5) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/udacity/boxes/ud381/versions/0.0.5/providers/virtualbox.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x metadata.json
x packer-virtualbox-ovf-1407201456-disk1.vmdk: Write failed
bsdtar: Error exit delayed from previous errors.

Please any help will be apprecialted thanks in advance.

**Comment by dpb587-pivotal** [comment]
Hi @MachineGamer - we're just users of vagrant and this repo is a vagrant box for bosh. Since this doesn't look like a bosh-lite issue, I recommend you follow up with the [vagrant community](https://github.com/mitchellh/vagrant) about these troubles.
