### ISSUE TITLE
Suport to `net.ipv4.tcp_keepalive_*` in bosh-lite containers

### ISSUE THREAD

**Issue by tscolari** [cloudfoundry/bosh-lite#329]
We noticed that some kernel properties available in the aws/vsphere stemcells are not present within the bosh-lite containers. This results is our releases not being able to be deployed to bosh-lite without specific work arounds.

The missing properties we found were:

```
net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_probes
net.ipv4.tcp_keepalive_time
```

**Comment by cppforlife** [comment]
@tscolari arguably if your release depends on these values you should set it up in the release.

though of course we want to make sure that bosh-lite env is exactly the same as the stemcell. we will at some point switch to using stemcell for the base image of bosh-lite.

**Comment by cppforlife** [comment]
@tscolari it doesnt look like garden (or may be procfs) propagate these values into a container. not sure if it's been done on purpose or not, but there is nothing that bosh-lite can do to fix this.

cc @goonzoid
