### ISSUE TITLE
bin/provision_cf fails

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/bosh-lite#331]
We updated the cloud config on a fresh bosh lite (9000.89.0, SHA 1a851c3) and then ran `bin/provision_cf`.

We got the following error:
```
Deploying
---------

Director task 5
  Started preparing deployment > Preparing deployment. Failed: Deployment manifest should not contain cloud config properties: ["compilation", "networks", "resource_pools"] (00:00:00)

Error 190014: Deployment manifest should not contain cloud config properties: ["compilation", "networks", "resource_pools"]

Task 5 error

For a more detailed error report, run: bosh task 5 --debug
```

Is bosh backwards compatible with older manifests that do not make use of cloud config?

**Comment by cppforlife** [comment]
@craigfurman once you opt-in for cloud config you have to edit your manifests for all deployments on that director. so not really backwards compatible in that way.

**Comment by karampok** [comment]
what about if you would like to overwrite something per deployment (in my case the  vm-anti-affinity https://bosh.io/docs/vm-anti-affinity.html)
