### ISSUE TITLE
Intermittent bosh agent client timeouts

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/bosh-lite#333]
We have been seeing intermittent timeouts in the agent client connection on recent versions of BOSH-lite (>= 9000.85). We see this manifest as the following behavior:

1. Deploy a 5-node cluster of the consul-release.
2. Change deployment to 3-node cluster.
3. Redeploy.
4. The deployment fails with either of these messages:
  - 'Timed out sending `drain`'
  - 'Timed out sending `prepare`'

When we look at the agent logs on the VMs that triggered the deployment, we see log lines like the following:

"2016-01-21_21:54:47.75061 [main] 2016/01/21 21:54:47 ERROR - App run Running agent: Sending heartbeat: Unresponsive client detected, connection dropped"

It then looks like the agent process on the VM restarted itself. If this were to have happened during a `drain` or `prepare` action, those actions would never be completed, thus leading to the timeout message reported by the director, and the resulting deployment error.

I have attached logs from two deployments that failed in this manner.
[timeout-logs.zip](https://github.com/cloudfoundry/bosh-lite/files/103737/timeout-logs.zip)

**Comment by cppforlife** [comment]
@ryanmoran can you include a manifest you are using so i can repro locally.

**Comment by ryanmoran** [comment]
Here are a couple manifests. You can deploy the 5-node cluster, and then the 3-node cluster to scale down. We would see the issue manifest about 1 in 5 attempts.

[yamls.zip](https://github.com/cloudfoundry/bosh-lite/files/105961/yamls.zip)

**Comment by cheeseblubber** [comment]
@ryanmoran The manifests has some keys and certs in them. Are these ok to be public?

**Comment by ryanmoran** [comment]
@cheeseblubber yes. there are no secrets in that manifest. The keys and certs were generated and only used here in this issue.

**Comment by mariash** [comment]
@ryanmoran did you start seeing this issue starting from certain version of bosh-lite? What version was working for you?

**Comment by ryanmoran** [comment]
@mariash we started seeing issues with 9000.88, but also continued to see issues after downgrading to 9000.85.

**Comment by cppforlife** [comment]
@ryanmoran garden team have found an issue (https://www.pivotaltracker.com/story/show/113553565). they are working to resolve it.

**Comment by ryanmoran** [comment]
@cppforlife great. thanks for the fast response.

**Comment by cppforlife** [comment]
we believe this was resolved in https://github.com/cloudfoundry/bosh-lite/releases/tag/9000.105.0
