### ISSUE TITLE
Creating container: the requested IP is already allocated

### ISSUE THREAD

**Issue by chakrapani123** [cloudfoundry/bosh-lite#334]
i am using bosh-lite to set-up concourse using https://github.com/concourse/concourse/blob/master/manifests/bosh-lite.yml

i have modified to fit ip range and facing this issue. i have tried vagrant reload and even bosh deploy --recreate and facing this issue . 

any help appreciated

**Comment by cppforlife** [comment]
Ensure that no other deployment is using 10.244.8.0/24.
