### ISSUE TITLE
Installation issue with Boshlite

### ISSUE THREAD

**Issue by Xhings** [cloudfoundry/bosh-lite#343]
Hello guys,

I am trying to get CF up and running on boshlite. Attached is the screen scratch of the installation steps followed, deploy.xml and debug logs for router job.

I tried fixing this with cck but could not get it up and running.Please let me know what am I missing.

[Issue.zip](https://github.com/cloudfoundry/bosh-lite/files/148577/Issue.zip)
Regards,
Xhings

**Comment by cppforlife** [comment]
@Xhings I'm not sure why router is failing. I would recommend opening the issue against cf-release. cc @Amit-PivotalLabs
