### ISSUE TITLE
bosh deploy in bosh-lite hangs on UAA job deployment step

### ISSUE THREAD

**Issue by ZeroGraviti** [cloudfoundry/bosh-lite#349]
Hi,
I am stuck at the bosh deploy step in bosh-lite. I have taken the approach as documented [here](http://docs.cloudfoundry.org/deploying/boshlite/) which references back to this github repo's readme. 
The output of `bosh vms` :-
```
vagrant@bosh-lite:~/cf-release$ bosh vms
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
Deployment `cf-warden'

Director task 42

Task 42 done

+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| VM                                                                        | State   | AZ  | VM Type  | IPs          |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (4b92e6f3-063d-444a-b02e-43b39c52339f)                           | running | n/a | large_z1
| 10.244.0.138 |
| blobstore_z1/0 (167d3ef7-e218-4548-8101-e2b25b4aee76)                     | running | n/a | medium_z1
| 10.244.0.130 |
| consul_z1/0 (76a9bb67-d3b0-4e0d-be8b-118487e896d8)                        | running | n/a | small_z1
| 10.244.0.54  |
| doppler_z1/0 (772f715e-5a47-4c3e-b3fd-b2c85464c4d4)                       | running | n/a | medium_z1
| 10.244.0.146 |
| etcd_z1/0 (f82c506d-0c2b-4861-9020-a009ac858a6e)                          | running | n/a | medium_z1
| 10.244.0.42  |
| ha_proxy_z1/0 (6c74591f-341f-4eb0-a2d9-709ca306fd75)                      | running | n/a | router_z1
| 10.244.0.34  |
| hm9000_z1/0 (861b7196-a404-4525-b229-fb1e22eead03)                        | running | n/a | medium_z1
| 10.244.0.142 |
| loggregator_trafficcontroller_z1/0 (0503827b-d731-4a43-893b-2a3a2364b3f2) | running | n/a | small_z1
| 10.244.0.150 |
| nats_z1/0 (81dd7301-6de8-495d-9c3d-969e853818f2)                          | running | n/a | medium_z1
| 10.244.0.6   |
| postgres_z1/0 (80c4a6b4-a358-46f1-b930-b20d9e078cd1)                      | running | n/a | medium_z1
| 10.244.0.30  |
| router_z1/0 (4e4100a3-aef2-4622-b776-2af616cda481)                        | running | n/a | router_z1
| 10.244.0.22  |
| runner_z1/0 (c0388082-e9bc-46b0-839b-25b2b7abcb7f)                        | running | n/a | runner_z1
| 10.244.0.26  |
| uaa_z1/0 (204cbdf2-d75d-46c9-a028-eefccd1a37d8)                           | stopped | n/a | medium_z1
| 10.244.0.134 |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+

VMs total: 13
```
shows that there is a stopped job (also where the entire deployment is stuck).
The bosh logs for the last director task (when I tried to restart _the_ stopped uaa_z1 job) can be found [here](https://gist.github.com/ZeroGraviti/5900a2ba3f0b399dc078). Looks like the `keytool` process is [maxing](http://pastebin.com/0miyuAnJ) out CPU on the vagrant host. BTW I have scaled down my requirements to **_5120Mb_** memory and **_2 CPUs_** in my Vagrantfile. I am running this on a local virtualbox vagrant provider.
This is the stemcell I am using:-
```
vagrant@bosh-lite:~/cf-release$ bosh deployments
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'

+-----------+--------------+--------------------------------------------------+--------------+
| Name      | Release(s)   | Stemcell(s)                                      | Cloud Config |
+-----------+--------------+--------------------------------------------------+--------------+
| cf-warden | cf/233+dev.1 | bosh-warden-boshlite-ubuntu-trusty-go_agent/3147 | none         |
+-----------+--------------+--------------------------------------------------+--------------+

Deployments total: 1
```
Here is the tail of the pending/hanging ouput from the bash window where I attempted to do a `bosh deploy` :-
  ```
Done compiling packages (00:28:20)

  Started creating missing vms
  Started creating missing vms > consul_z1/0 (76a9bb67-d3b0-4e0d-be8b-118487e896d8)
  Started creating missing vms > ha_proxy_z1/0 (6c74591f-341f-4eb0-a2d9-709ca306fd75)
  Started creating missing vms > nats_z1/0 (81dd7301-6de8-495d-9c3d-969e853818f2)
  Started creating missing vms > etcd_z1/0 (f82c506d-0c2b-4861-9020-a009ac858a6e)
  Started creating missing vms > blobstore_z1/0 (167d3ef7-e218-4548-8101-e2b25b4aee76)
  Started creating missing vms > postgres_z1/0 (80c4a6b4-a358-46f1-b930-b20d9e078cd1)
  Started creating missing vms > uaa_z1/0 (204cbdf2-d75d-46c9-a028-eefccd1a37d8)
  Started creating missing vms > hm9000_z1/0 (861b7196-a404-4525-b229-fb1e22eead03)
  Started creating missing vms > api_z1/0 (4b92e6f3-063d-444a-b02e-43b39c52339f)
  Started creating missing vms > runner_z1/0 (c0388082-e9bc-46b0-839b-25b2b7abcb7f)
  Started creating missing vms > doppler_z1/0 (772f715e-5a47-4c3e-b3fd-b2c85464c4d4)
  Started creating missing vms > loggregator_trafficcontroller_z1/0 (0503827b-d731-4a43-893b-2a3a2364b3f2)
  Started creating missing vms > router_z1/0 (4e4100a3-aef2-4622-b776-2af616cda481)
     Done creating missing vms > ha_proxy_z1/0 (6c74591f-341f-4eb0-a2d9-709ca306fd75) (00:00:34)
     Done creating missing vms > postgres_z1/0 (80c4a6b4-a358-46f1-b930-b20d9e078cd1) (00:00:34)
     Done creating missing vms > router_z1/0 (4e4100a3-aef2-4622-b776-2af616cda481) (00:00:34)
     Done creating missing vms > loggregator_trafficcontroller_z1/0 (0503827b-d731-4a43-893b-2a3a2364b3f2) (00:00:34)
     Done creating missing vms > nats_z1/0 (81dd7301-6de8-495d-9c3d-969e853818f2) (00:00:35)
     Done creating missing vms > hm9000_z1/0 (861b7196-a404-4525-b229-fb1e22eead03) (00:00:36)
     Done creating missing vms > runner_z1/0 (c0388082-e9bc-46b0-839b-25b2b7abcb7f) (00:00:36)
     Done creating missing vms > consul_z1/0 (76a9bb67-d3b0-4e0d-be8b-118487e896d8) (00:00:37)
     Done creating missing vms > api_z1/0 (4b92e6f3-063d-444a-b02e-43b39c52339f) (00:00:37)
     Done creating missing vms > blobstore_z1/0 (167d3ef7-e218-4548-8101-e2b25b4aee76) (00:00:37)
     Done creating missing vms > etcd_z1/0 (f82c506d-0c2b-4861-9020-a009ac858a6e) (00:00:37)
     Done creating missing vms > doppler_z1/0 (772f715e-5a47-4c3e-b3fd-b2c85464c4d4) (00:00:36)
     Done creating missing vms > uaa_z1/0 (204cbdf2-d75d-46c9-a028-eefccd1a37d8) (00:00:37)
     Done creating missing vms (00:00:37)

  Started updating job consul_z1 > consul_z1/0 (76a9bb67-d3b0-4e0d-be8b-118487e896d8). Done (00:00:40)
  Started updating job ha_proxy_z1 > ha_proxy_z1/0 (6c74591f-341f-4eb0-a2d9-709ca306fd75). Done (00:00:40)
  Started updating job nats_z1 > nats_z1/0 (81dd7301-6de8-495d-9c3d-969e853818f2). Done (00:00:22)
  Started updating job etcd_z1 > etcd_z1/0 (f82c506d-0c2b-4861-9020-a009ac858a6e). Done (00:00:42)
  Started updating job blobstore_z1 > blobstore_z1/0 (167d3ef7-e218-4548-8101-e2b25b4aee76). Done (00:00:47)
  Started updating job postgres_z1 > postgres_z1/0 (80c4a6b4-a358-46f1-b930-b20d9e078cd1). Done (00:00:40)
  Started updating job uaa_z1 > uaa_z1/0 (204cbdf2-d75d-46c9-a028-eefccd1a37d8)
```

**Comment by fhanik** [comment]
do a `vagrant box update` - we believe there was one version that would have an issue, and causing the UAA pre-start script to hang. We are no longer able to reproduce it.

**Comment by ZeroGraviti** [comment]
This is my box version as per the Vagrantfile : 9000.94.0. I have also taken care to checkout the tag for bosh-lite which corresponds to this. Is my assumption that the tag 9000.94.0 on bosh-lite matching this will work ? Is there a related tag/branch on [cf-release](https://github.com/cloudfoundry/cf-release/) which I need to checkout ?

**Comment by ZeroGraviti** [comment]
I am doing the cf-release git c/o and all the subsequent steps in the vbox after 'vagrant sshing' to it. Must I do this on the vbox host instead ?

**Comment by ematpl** [comment]
@ZeroGraviti: Please either upgrade to BOSH-Lite box version 9000.103.0 or later, or downgrade to 9000.84.0 or earlier. The pre-start script failure and CPU usage are related to a bug in the Linux kernel that affects teardown of processes interacting with an AUFS filesystem (such as those running in containers on BOSH-Lite). [This cf-dev thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/VNFKTVQN42SMDNXHA7PWP2K37JQD2I3I/#VNFKTVQN42SMDNXHA7PWP2K37JQD2I3I) has more information, but you're likely to see this problem if the version of the Linux kernel in your BOSH-Lite VM is between 3.19.0-40 and 3.19.0-50 (inclusive). 9000.84.0 has kernel version 3.19.0-39, and 9000.103.0 has 3.19.0-51, so neither of them will exhibit this problem.

Thanks,
Eric, CF Runtime Diego PM

**Comment by ZeroGraviti** [comment]
Perfect... This works.

**Comment by ZeroGraviti** [comment]
@ematpl Can you please guide me to the build number which will have Diego (garden) instead of DEA (warden) ? `9000.103.0` seems to be DEA.

**Comment by ematpl** [comment]
Hi, @ZeroGraviti,

You seem to be conflating the use of garden and warden in BOSH-Lite with its use in CF and Diego.

- BOSH-Lite currently uses garden-linux to make BOSH-deployed "VMs" as containers in a single virtual machine via the "warden" CPI. It used to use warden for this, but it has used garden-linux since at least build 9000.50.0, and maybe earlier. You can observe this if you use `vagrant ssh` to log into a BOSH-Lite VM and inspect the running processes or run `monit summary`.
- CF manages containerized applications across a cluster of VMs. The "default" container runtime in CF is still the DEAs, which are tightly coupled to warden as their containerizer, and those are the VMs that come with the deployment-manifest generation scripts in the [CF BOSH release](https://github.com/cloudfoundry/cf-release).
- Diego provides a new container runtime that manages containers via the Garden API. [Its BOSH release](https://github.com/cloudfoundry-incubator/diego-release) has scripts that produce manifests suitable for deploying alongside an existing CF deployment. These manifests also use garden-linux from [its own BOSH release](https://github.com/cloudfoundry-incubator/garden-linux-release). In the near-to-mid future, the manifest tooling for CF will also be capable of generating deployment manifests with jobs from Diego.

Best,
Eric

**Comment by JakimLi** [comment]
I am having this problem even with 9000.137.0, it gives a message "No artifact found for uaa" and then hanging on Pre-packaging... for a ver long time, please help.

here is some output:
```
Building statsd_injector...
  Using final version 'c7ac37ac334c2f5120f114dd5d82389f202645b7'

Building syslog_drain_binder...
  Using final version '0939a8e422f7729c7a5d641e39b1fa720dc346be'

Building tps...
  Using final version '0eace0b29d9c2a177c5e2ae36c7b3c1e5628f96b'

Building uaa...
  No artifact found for uaa
  Generating...
  Pre-packaging...
```

**Comment by svrc-pivotal** [comment]
This is happening again on 9000.137.0 - was working for weeks .
