### ISSUE TITLE
vagrant up aws fails on private_key_path

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-lite#350]
I would like to deploy bosh-lite to AWS. 

Following instructions from https://github.com/cloudfoundry/bosh-lite/blob/master/docs/aws-provider.md

```
$ vagrant up --provider=aws
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: ~/.ssh/id_rsa_bosh
```

What is the private key for? 

It would be helpful if the instructions said something like:

> An SSH keypair is required to ______. If you do not already have one, generate an SSH keypair for use with BOSH Lite. By default, Vagrant expects to find the private key at `~/.ssh/id_rsa_bosh`.  You can use the `BOSH_LITE_PRIVATE_KEY`  environment variable to change where Vagrant looks for the private key. 

Ultimately got through this by creating a keypair, but I'm still not sure what it's for, and not having this spelled out in the instructions wasted 30 minutes.

```
$ vagrant --version
Vagrant 1.8.1

$ vagrant box list
cloudfoundry/bosh-lite (aws, 9000.104.0)
```

**Comment by cppforlife** [comment]
Docs were merged.
