### ISSUE TITLE
Several confusing points in the AWS instructions

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-lite#351]
https://github.com/cloudfoundry/bosh-lite/blob/master/docs/aws-provider.md

> This similarly applies to steps 7-9, below.

There are no step numbers, nor are there nine bullets. 

> Make sure the security group you are using in the Vagrantfile exists

The instructions say nothing about adding a security group to the Vagrantfile. I do not expect to have to edit the Vagrantfile; I've never had to do this running BOSH Lite locally. The instructions say to put the security group in the `BOSH_LITE_SECURITY_GROUP` environment variable. Maybe this note about the Vagrantfile should be removed.

**Comment by cppforlife** [comment]
Updated.
