### ISSUE TITLE
vagrant up aws fails - security group does not exist

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-lite#352]
```
$ echo $BOSH_LITE_SECURITY_GROUP
sg-df7de2b8
```

This VPC is in us-east-1.
The VPC allows all inbound.

```
$ vagrant up --provider aws
Bringing machine 'default' up with 'aws' provider...
==> default: Checking if box 'cloudfoundry/bosh-lite' is up to date...
/Users/shannon/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/action/run_instance.rb:98: warning: duplicated key at line 100 ignored: :associate_public_ip
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: m3.xlarge
==> default:  -- AMI: ami-5670703c
==> default:  -- Region: us-east-1
==> default:  -- Keypair: bosh
==> default:  -- Security Groups: ["sg-df7de2b8"]
==> default:  -- Block Device Mapping: [{:DeviceName=>"/dev/sda1", "Ebs.VolumeType"=>"gp2", "Ebs.VolumeSize"=>80}]
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Source Destination check:
==> default:  -- Assigning a public IP address in a VPC: false
==> default:  -- VPC tenancy specification: default
==> default: Warning! Vagrant might not be able to SSH into the instance.
==> default: Please check your security groups settings.
/Users/shannon/.vagrant.d/gems/gems/excon-0.48.0/lib/excon/middlewares/expects.rb:6:in `response_call': The security group 'sg-df7de2b8' does not exist (Fog::Compute::AWS::NotFound)
```

```
$ vagrant --version
Vagrant 1.8.1

$ vagrant box list
cloudfoundry/bosh-lite (aws, 9000.104.0)
```

**Comment by cppforlife** [comment]
Seems like an issue with your VPC. Security group you have specific does not exist: `The security group 'sg-df7de2b8' does not exist`.

**Comment by shalako** [comment]
The security group does exist. 

![screen shot 2016-03-23 at 10 45 58 am](https://cloud.githubusercontent.com/assets/156568/13994903/22e89c50-f0e4-11e5-848b-f271d656ef96.png)
![screen shot 2016-03-23 at 10 47 23 am](https://cloud.githubusercontent.com/assets/156568/13994917/38a31066-f0e4-11e5-9d26-b030dfd443a8.png)

**Comment by shalako** [comment]
Why can't I re-open this issue?

**Comment by dpb587-pivotal** [comment]
The security group is within your VPC, but it looks like you haven't configured the `BOSH_LITE_SUBNET_ID` so the VM is not going to be in the VPC.

You can use either the EC2-Classic, default security group (`sg-4e59bc25` in your case) or specify the subnet you want to use with `BOSH_LITE_SUBNET_ID`.

**Comment by shalako** [comment]
Thank you, @dpb587-pivotal 

Is the following correct?

- When using EC2-Classic, you must set `BOSH_LITE_SECURITY_GROUP`
- When using a VPC, you must set both `BOSH_LITE_SECURITY_GROUP` and `BOSH_LITE_SUBNET_ID`

If so, please update the documentation.The current statement, "You may have to set additional environment variables listed below depending on your environment" is not helpful.
