### ISSUE TITLE
I deployment the lastest version of cf-release,but the deployment task are hanging at uaa.

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/bosh-lite#354]
Hi:

My cf-release version are v233,when i deployment it in bosh-lite, i found it hung at uaa(pre-start script)

The box version is 9000.105,the issue some like this [Docker 1.9.1 hanging at build step "Setting up ca-certificates-java"](https://github.com/docker/docker/issues/18180)

Can i upgrade my kernel from 3.19.0-49-generic to 4.2.0-34-generic? And will this operator effect our garden-linux.

Thanks.

**Comment by ematpl** [comment]
Hi, @wdxxs2z,

Are you sure your active VM is actually on box version 9000.105.0? I just destroyed and recreated my BOSH-Lite VM at that version, and it's on kernel version 3.19.0-56-generic, which should not have these issues with the UAA pre-start script.

Thanks,
Eric
