### ISSUE TITLE
ERROR: vagrant up --provider=virtualbox

### ISSUE THREAD

**Issue by junneyang** [cloudfoundry/bosh-lite#367]
A customization command failed: ["modifyvm", :id, "--paravirtprovider", "minimal"]

screenshot:
![qq 20160519100916](https://cloud.githubusercontent.com/assets/6802322/15380514/c65aa01c-1da9-11e6-9b17-5c1bc7150416.png)

**Comment by dpb587-pivotal** [comment]
Hi - please try upgrading VirtualBox to 5+ (see this [troubleshooting.md](https://github.com/cloudfoundry/bosh-lite/blob/develop/docs/troubleshooting.md#customization-command-failed) page for more details).

**Comment by junneyang** [comment]
@dpb587-pivotal 
thanks! it works!
