### ISSUE TITLE
ERROR: ./bin/provision_cf  

### ISSUE THREAD

**Issue by junneyang** [cloudfoundry/bosh-lite#369]
git submodule update --init --recursive --force  ERROR:
fatal: insanely long object directory

screenshot:
![qq 20160520105307](https://cloud.githubusercontent.com/assets/6802322/15415950/1015f86c-1e79-11e6-91f1-a57dc9d775e7.png)

thanks!

**Comment by dpb587-pivotal** [comment]
Windows historically doesn't like long file paths. You can try enabling support within git by...

    git config --system core.longpaths true

**Comment by junneyang** [comment]
@dpb587-pivotal 
i set already, it not works.

**Comment by dpb587-pivotal** [comment]
I see you've raised the issue upstream at https://github.com/git-for-windows/git/issues/762 and https://github.com/git-for-windows/git/issues/342. This issue can probably be closed.
