### ISSUE TITLE
Add short 'what is bosh-lite section'

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/bosh-lite#370]
In trying to figure out what bosh-lite does or the problem it solves, I'm checking the README.md and the project description. Neither seem to explain what bosh-lite does other than `A lite development env for BOSH`, which is fairly nondescriptive. Could we have a section outlining what it does or the context it's used in?

**Comment by dpb587-pivotal** [comment]
Hi - bosh-lite is a pretty specific solution for [BOSH](https://bosh.io) development work, which I think the "A local development environment for BOSH using Warden containers in a Vagrant box." part from the [readme](https://github.com/cloudfoundry/bosh-lite/blob/4a94e14eaab52748ffd0c9730eb398139de1c860/README.md) attempts to describe. It does kind of assume you're at least familiar with the BOSH ecosystem.

Perhaps it'd be helpful if you could describe how you found this repo so we can better know your context and who else we should be describing it to.

**Comment by kitemongerer** [comment]
I have recently started using BOSH and asked a coworker what bosh-lite is. He brought up the GitHub page assuming bosh-lite devs would be better at explaining it but there wasn't much explanation. Just a suggestion to help people exploring bosh-lite for the first time who may not be overly familiar with bosh.

**Comment by dpb587-pivotal** [comment]
@cppforlife, perhaps this repo's URL could point to https://bosh.io/docs/bosh-lite.html where bosh-lite is summarized a bit better.

Separately, I also notice bosh-lite doesn't link to http://bosh.io/docs/warden-cpi.html which may also be a useful link somewhere in the readme.

**Comment by cppforlife** [comment]
@dpb587-pivotal sounds reasonable. will update readme.

**Comment by cppforlife** [comment]
Updated README with a bit more info. Feel free to reopen if you think more information should be included.
