### ISSUE TITLE
Is there a sucessful way to set up bosh cli in windows ??

### ISSUE THREAD

**Issue by jaikanthm** [cloudfoundry/bosh-lite#376]
Trying to setup bosh cli in windows and have not been successful yet

**Comment by dpb587-pivotal** [comment]
Hi - the cli doesn't currently support Windows. Since you created this issue on bosh-lite, I assume that is what you're using? If that's true, the `bosh` CLI is pre-installed in the bosh-lite VM, so what you could do is `vagrant ssh` and use the `bosh` command from inside the VM.

**Comment by cppforlife** [comment]
Closing. We'll update docs when bosh-cli supports Windows.

**Comment by jaikanthm** [comment]
thanks guys I did the same and I was somehow able to get bosh cli working directly from windows by installing the ruby dependencies but yeah ssh looks like a much easier option

**Comment by otupytska** [comment]
Hi. Could you please clarify availability of bosh CLI on Windows.
I was able to install bosh CLI on Windows via gem and all commands were working.
But I got following exception during creating release of my project:
Cannot create tarball: tar (child): Cannot connect to C: resolve failed
tar: C\:/Users/USER~1/AppData/Local/Temp/d20170203-8668-11opgm0/ruby20170203-8668-1rp5rgc.tgz: Cannot write: Broken pipe
tar: Child returned status 128

Is bosh CLI still shouldn't be used on Windows?

**Comment by allomov** [comment]
@otupytska from what I know there is no official support for windows for bosh_cli ruby gem. But did you try a new [bosh-cli in golang](https://github.com/cloudfoundry/bosh-cli)? Since it is built in golang you can try to compile it on your windows host.

**Comment by otupytska** [comment]
@allomov didn't here about new bosh-cli. Will try, thanks!

**Comment by shivdeepnv** [comment]
Hi Team, I am following the instructions in the link - [](https://bosh.io/docs/bosh-lite) https://bosh.io/docs/bosh-lite

I installed Bosh CLI using gem install on Windows (since it was an auto install, it picked up the version BOSH 1.3262.26.0)

Now, I need to install the BOSH Director VM for which I need to execute -

`$ bosh create-env ~/workspace/bosh-deployment/bosh.yml \`

but, it looks like create-env is an unknown command. How do I go about this?

**Comment by Infra-Red** [comment]
@shivdeepnv You should install Bosh CLI v2, `bosh create-env` command is not available in ruby bosh cli. https://bosh.io/docs/cli-v2.html#install

**Comment by ivandavidov** [comment]
@shivdeepnv - You are using the Ruby based bosh CLI (which is v1) but the instructions say that you have to install bosh CLI v2. I f you install bosh CLI v2 you will find out that the ``create-env`` command is valid.

https://bosh.io/docs/cli-v2.html#install

**Comment by shivdeepnv** [comment]
Thanks @Infra-Red and @ivandavidov. I tried this, but it does not execute correctly. I downloaded bosh-cli-2.0.28-windows-amd64.exe and tried executing this, but it opens up a command prompt and it immediately closes. When I check the version of CLI it still states V 1.3xxxx

**Comment by ivandavidov** [comment]
I strongly suggest that you try this with Linux instead of Windows. I know that all of this should work on Windows but IMHO you will get much better results and user experience in Linux.

**Comment by xu-chenyang** [comment]
maybe no people still care about this, but here is a way to fix? this issue.  @shivdeepnv 
(not sure is this the right way to do though...)
1. change the file name into bosh.exe.
2.move the file to ....../system32/
3.run bosh -v on cmd.
4.you can use bosh command on windows now.
