### ISSUE TITLE
Default properties in Job spec not being used.

### ISSUE THREAD

**Issue by Freyert** [cloudfoundry/bosh-lite#380]
I've defined a variety of default values for template variables in my job spec and they are not being picked up.

The deployment is also not using variables I've specified in the properties block of my manifest.

**Comment by dpb587-pivotal** [comment]
@Freyert - is this related to the question you brought up in [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/bosh/p1467390464001531)? If so, can this be closed?

**Comment by cppforlife** [comment]
Seems like problem was resolved over slack.
