### ISSUE TITLE
Unable to start Bosh-Lite after Host machine restart

### ISSUE THREAD

**Issue by phanikumar1210** [cloudfoundry/bosh-lite#381]
I am new to Cloud foundry and I have installed Bosh-lite on Ubuntu machine. It worked fine till I have restarted the physical machine. But after restarting the host I brought the vagrant Box up and running and found that the services of Bosh are not working. So I ran bosh cck --auto and got an error specifying **Please choose deployment first**. It would be a great help to me if some one could suggest on how to resolve this issue.

**Comment by dpb587-pivotal** [comment]
Hi - can you provide more details about the which instructions you were following? The [cf docs](http://docs.cloudfoundry.org/deploying/boshlite/create_a_manifest.html) should have automatically updated your deployment. Alternatively, you can manually run `bosh deployment {wherever-you-cloned-cf-release}/bosh-lite/deployments/cf.yml` and try running `cck` again.

**Comment by phanikumar1210** [comment]
when I am running the above command I am getting an error specifying **Failed_blobstore_z1/0 (92****9)  is not running after update** and was unable to start the VM's of bosh. All the VM's are showing as unrensponsive as status in bosh vms command.

**Comment by 7hunderbird** [comment]
Please also ensure you've re-run `./bin/add-route` to re-establish the network routes.

**Comment by cppforlife** [comment]
Documentation update was merged. If bosh deploy fails feel free to open issue against cf-release.
