### ISSUE TITLE
vagrant up --provider=virtualbox ERROR

### ISSUE THREAD

**Issue by MohanBunny** [cloudfoundry/bosh-lite#384]
Hi,
I am completely new to vagrant and bosh-cli...
I just gone through the documents to learn about bosh.
when i followed the doc, the initial step is to install vagrant in our local machine.so i started and followed all the steps.
when I run the command
**vagrant up --provider=virtualbox**
it given me error as **There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling virtualbox**

the complete logs are..

**Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'cloudfoundry/bosh-lite' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "ddf3ae79-8885-4cac-a5fe-eb83660b295a", "--type", "headless"]

Stderr: VBoxManage: error: Failed to load R0 module /usr/lib/virtualbox/VMMR0.r0: World writable: '/usr' (VERR_SUPLIB_WORLD_WRITABLE).
VBoxManage: error: Failed to load VMMR0.r0 (VERR_SUPLIB_WORLD_WRITABLE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole**

I dont understand anything from these logs.
Please suggest me for the same.

thanks in advance.
Mohan.V

**Comment by dpb587-pivotal** [comment]
I haven't personally seen this before, but a search for the error turns up this [forum topic](http://forums.macrumors.com/threads/virtual-box-problem-solved.1196027/) which suggests double checking your `/Applications` and `/Applications/Virtualbox.app` directory permissions. Might want to try that?
