### ISSUE TITLE
bosh-lite AMI based on HVM

### ISSUE THREAD

**Issue by tario-yang** [cloudfoundry/bosh-lite#385]
From the AWS console, there is no AMI based on hvm. Is it planned to release this? Thanks!

**Comment by 7hunderbird** [comment]
BOSH-lite is for development.  It's CPI is Vagrant, not AWS.

If you're looking for a stemcell for AWS that is HVM, here's a blog article I wrote about [how to choose a stemcell](http://www.starkandwayne.com/blog/how-to-choose-a-stemcell/).

The AWS HVM is a "Light" version and is referenced in your manifest, hosted on AWS and then once you're on your BOSH Director in AWS it will [import the AMI](http://bosh.io/docs/build-stemcell.html#light-stemcells) it needs when compiling a build.

**Comment by ljfranklin** [comment]
👍 to adding this from a user on slack. They were trying to use one of the newer instance types and hit this error:

```
Virtualization type 'hvm' is required for instances of type 'c4.4xlarge'.
```

https://cloudfoundry.slack.com/archives/bosh/p1472137180003444

**Comment by jchesterpivotal** [comment]
Yep, this was me. Amazon's [matrix of PV vs HVM instances](https://aws.amazon.com/amazon-linux-ami/instance-type-matrix/) is illuminating.

My gut sense is that they'll eventually retire PV entirely, or relegate it to an even backer back-water.

**Comment by StanleyShen** [comment]
@7hunderbird If I am using bosh-lite on AWS, since the director is hosted in the VM we are trying to launch, which means we cannot "upload the stemcell to director".

I think we need to release an AMI based on HVM so that we can have more choice.

**Comment by 7hunderbird** [comment]
@StanleyShen have you tried configuring your manifest to use a AWS Xen-HVM Light stemcell?

**Comment by StanleyShen** [comment]
How can I configure this in vagrant file?

**Comment by 7hunderbird** [comment]
Have you configured it either with the environment variable or in the `Vagrantfile`?

From your CLI before you run `vagrant up --provider aws`:

```
export BOSH_LITE_INSTANCE_TYPE=m4.xlarge
```

Or in the `Vagrantfile`:

```
  config.vm.provider :aws do |v, override|
  ...
    v.instance_type = 'm4.xlarge'
  end
```

What is the error you get when you try to provision the instance?

**Comment by 7hunderbird** [comment]
I got this error when I tried to do some of the above.

```
There was an error talking to AWS. The error message is shown
below:

InvalidParameterCombination => Virtualization type 'hvm' is required for instances of type 'm4.xlarge'. Ensure that you are using an AMI with virtualization type 'hvm'. For more information, see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html
```

So I downloaded the stemcell https://d26ekeud912fhb.cloudfront.net/bosh-stemcell/aws/light-bosh-stemcell-3263.5-aws-xen-hvm-ubuntu-trusty-go_agent.tgz

And looked at the AMI name from the `stemcell.MF` for the region I'm using.

For example, using "us-west-2" the ami is: `ami-abfc22cb`.

To configure this in the `Vagrantfile` add this to the end of the `config.vm.provider :aws do |v, override|` block:

```
    v.region_config "us-west-2" do |region|
      region.ami = "ami-abfc22cb"
    end
```

This got it to start provisioning when I had most of my environment variables setup correctly.  Let me know if this helps you get further along.

**Comment by StanleyShen** [comment]
Thanks for information.
I tried your settings, and I see the VM is up for a while and then it's stopped automatically.

And "vagrant up --provider=aws" freezing at this log information:
```
07:22:55 [K    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[K==> default: Successfully added box 'cloudfoundry/bosh-lite' (v9000.131.0) for 'aws'!
07:22:56 ==> default: Checking if box 'cloudfoundry/bosh-lite' is up to date...
07:22:57 ==> default: Warning! The AWS provider doesn't support any of the Vagrant
07:22:57 ==> default: high-level network configurations (`config.vm.network`). They
07:22:57 ==> default: will be silently ignored.
07:22:57 ==> default: Warning! You're launching this instance into a VPC without an
07:22:57 ==> default: elastic IP. Please verify you're properly connected to a VPN so
07:22:57 ==> default: you can access this machine, otherwise Vagrant will not be able
07:22:57 ==> default: to SSH into it.
07:22:57 ==> default: Launching an instance with the following settings...
07:22:57 ==> default:  -- Type: m4.xlarge
07:22:57 ==> default:  -- AMI: ami-abfc22cb
07:22:57 ==> default:  -- Region: us-west-2
07:22:57 ==> default:  -- Keypair: bosh
07:22:57 ==> default:  -- Subnet ID: subnet-12345567
07:22:57 ==> default:  -- Security Groups: ["sg-12345647"]
07:22:57 ==> default:  -- Block Device Mapping: [{:DeviceName=>"/dev/sda1", "Ebs.VolumeType"=>"gp2", "Ebs.VolumeSize"=>120}]
07:22:57 ==> default:  -- Terminate On Shutdown: false
07:22:57 ==> default:  -- Monitoring: false
07:22:57 ==> default:  -- EBS optimized: false
07:22:57 ==> default:  -- Source Destination check: 
07:22:57 ==> default:  -- Assigning a public IP address in a VPC: true
07:22:57 ==> default:  -- VPC tenancy specification: default
07:22:58 ==> default: Waiting for instance to become "ready"...
07:23:12 ==> default: Waiting for SSH to become available...
```

**Comment by TCSCMAPIVOTAL** [comment]
Same as @StanleyShen 

Bringing machine 'default' up with 'aws' provider...
==> default: Checking if box 'cloudfoundry/bosh-lite' is up to date...
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: t2.xlarge
==> default:  -- AMI: ami-abfc22cb
==> default:  -- Region: us-west-2
==> default:  -- Keypair: cfec2
==> default:  -- Subnet ID: subnet-c52ca28d
==> default:  -- Elastic IP: *********
==> default:  -- Security Groups: ["*********"]
==> default:  -- Block Device Mapping: [{:DeviceName=>"/dev/sda1", "Ebs.VolumeType"=>"gp2", "Ebs.VolumeSize"=>80}]
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Source Destination check:
==> default:  -- Assigning a public IP address in a VPC: false
==> default:  -- VPC tenancy specification: default
==> default: Warning! Vagrant might not be able to SSH into the instance.
==> default: Please check your security groups settings.
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...


Any idea ?

**Comment by dpb587-pivotal** [comment]
@TCSCMAPIVOTAL When hanging on "Waiting for SSH", it typically means security groups are misconfigured. Double check the configuration used, or consider using [bosh-deployment](http://bosh.io/docs/bosh-lite.html#install).

**Comment by dpb587-pivotal** [comment]
We are no longer producing AMIs for bosh-lite and this method is deprecated. Instead, you can try deploying bosh-lite (with the `bosh-lite*.yml` ops files like [these docs](http://bosh.io/docs/bosh-lite.html#install)) via bosh-deployment (which uses the normal stemcells).
