### ISSUE TITLE
Vagrant up on current bosh-lite Vagrant Box

### ISSUE THREAD

**Issue by matthewbaldwin** [cloudfoundry/bosh-lite#386]
I needed to do the following on the bosh-lite box

Errors:

default: Warning: Authentication failure. Retrying...

for me, this was resolved by changing the permissions on .ssh folder in vagrant home directory (i.e. "~vagrant/.ssh"). I think I messed up the permissions when I was setting up ssh keys for my application.

It seems that 'authorized_keys' file must be 'rw' only for 'vagrant' user so "chmod 600 authorized_keys"; the same goes for the directory itself and its parent:

so:

chmod 600 authorized_keys
chmod 700 .
chmod 700 ..

**Comment by matthewbaldwin** [comment]
Running Vagrant 1.8.5 and VBox Version 5.1.2 r108956

**Comment by abhikco** [comment]
This is related to: https://github.com/mitchellh/vagrant/issues/7610

**Comment by abbi-gaurav** [comment]
+1

**Comment by aaronshurley** [comment]
+1 on VBox 5.1.6 and Vagrant 1.8.5

**Comment by jiangytcn** [comment]
+1

**Comment by mfine30** [comment]
+1

**Comment by dpb587-pivotal** [comment]
Closing - Vagrant 1.8.6 is released and confirmed to fix this issue.
