### ISSUE TITLE
Not able to set cf api , though bosh vms shows all vms are up and running

### ISSUE THREAD

**Issue by madhumm** [cloudfoundry/bosh-lite#388]
Hi, 

I'm trying to setup Cloud Foundry with bosh-lite on my local machine.  I went through all the setup from github and cloud foundry documentation .   cf api gives 404 when I try to set that. Following are details: 

1.   Following is the response: 
CF_TRACE=true cf api --skip-ssl-validation https://api.bosh-lite.com

VERSION:
6.6.1-b2cdb2b

Setting api endpoint to https://api.bosh-lite.com...

REQUEST: [2016-08-13T13:37:16Z]
GET /v2/info HTTP/1.1
Host: api.bosh-lite.com
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.6.1-b2cdb2b / linux

RESPONSE: [2016-08-13T13:37:21Z]
HTTP/1.1 404 Not Found
Content-Length: 69
Content-Type: text/plain; charset=utf-8
Date: Sat, 13 Aug 2016 13:37:20 GMT
X-Cf-Routererror: unknown_route
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: e78e7049-beb9-4c6a-5070-5731c2b5b9cf

404 Not Found: Requested route ('api.bosh-lite.com') does not exist.

FAILED
Server error, status code: 404, error code: 0, message:
FAILED
Server error, status code: 404, error code: 0, message:

I verified the bosh vms and they're running :

vagrant@vagrant-ubuntu-trusty-64:~$ bosh vms
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'
Deployment 'cf-warden'

Director task 131

Task 131 done

+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs          |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (dc481f2e-7792-438c-90be-a5ef9bbc8d6e)                           | running | n/a | large_z1  | 10.244.0.138 |
| blobstore_z1/0 (7bc9572d-dc7a-4b14-af34-40e39d7cae97)                     | running | n/a | medium_z1 | 10.244.0.130 |
| consul_z1/0 (874c30ff-c90e-4f41-b287-19f8ac5a1d19)                        | running | n/a | small_z1  | 10.244.0.54  |
| doppler_z1/0 (96348ad7-951d-41e2-8a75-0891ceab6b03)                       | running | n/a | medium_z1 | 10.244.0.146 |
| etcd_z1/0 (38a52b12-9f99-4a39-aaee-cf2831c62de0)                          | running | n/a | medium_z1 | 10.244.0.42  |
| ha_proxy_z1/0 (b9bafa8c-f068-434b-8c5b-e27b1f51aef9)                      | running | n/a | router_z1 | 10.244.0.34  |
| hm9000_z1/0 (28ca6f3f-7940-4e61-8aff-a55ff192d874)                        | running | n/a | medium_z1 | 10.244.0.142 |
| loggregator_trafficcontroller_z1/0 (26d7a7b6-2668-4123-84d4-e39637e17faa) | running | n/a | small_z1  | 10.244.0.150 |
| nats_z1/0 (91b1aa98-ed99-4ba4-94bc-d3bd177df1b1)                          | running | n/a | medium_z1 | 10.244.0.6   |
| postgres_z1/0 (e185f4e2-2ad7-4b64-bc6f-9ec99ce365c6)                      | running | n/a | medium_z1 | 10.244.0.30  |
| router_z1/0 (5a8a30e1-9dc6-4b5c-af57-2fc73ddefda7)                        | running | n/a | router_z1 | 10.244.0.22  |
| runner_z1/0 (2c02e4b7-4f2e-4985-8669-052607a08469)                        | running | n/a | runner_z1 | 10.244.0.26  |
| uaa_z1/0 (3e812015-3df0-40d6-aa4c-727faf56eb7e)                           | running | n/a | medium_z1 | 10.244.0.134 |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+

VMs total: 13

 
api.bosh-lite.com resolves to 

api.bosh-lite.com has address 10.244.0.34

Any suggestions are appreciated ? Thank you. 

Thanks
Madhu

**Comment by 7hunderbird** [comment]
Can you try running `.bin/add-route` to see if this can help ensure the networking routes are configured correctly?

**Comment by madhumm** [comment]
Thanks for the reply.  Yes, after trying for several times, this ./bin/add-route.  Thanks for reply.

**Comment by sohammondal** [comment]
@madhumm 
![capture](https://user-images.githubusercontent.com/34343502/45799333-bcb20880-bcca-11e8-8715-9155b3b0af69.PNG)
I am getting this error. ./bin/add-route not working for me. Could you please help me how to solve this ?
