### ISSUE TITLE
unable to recreate the bosh-lite containers with bosh cck after host machine restart

### ISSUE THREAD

**Issue by rphukan** [cloudfoundry/bosh-lite#393]
I see that there are already two open issues #353 and #381 similar to this. But both of them did not help me to  resolve my problem and hence creating a new one with my problem description. Hope someone would be able to help me.

```
BOSH 1.3262.4.0
vagrant box 'cloudfoundry/bosh-lite' version '9000.126.0'
```

After I restarted my Ubuntu machine where I have this setup , I am trying to recreate the VMs(containers) for the CF components with `bosh cck`. But it is not able to recreate all the VMs and fails with the below error

```
Error 100: Error resolving problem `41': `runner_z1/0 (133871bd-56f8-4cf6-a259-4db64d623be1)' is not running after update. Review logs for failed jobs: consul_agent
Error resolving problem `43': Action Failed get_task: Task 5b9f0aff-de9b-43bf-70ba-46c40d497ccc result: 1 of 5 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: route_registrar, cloud_controller_clock, cloud_controller_worker, consul_agent.
Error resolving problem `44': `router_z1/0 (26898146-19a7-441a-81e8-f90c37e3023a)' is not running after update. Review logs for failed jobs: consul_agent
Error resolving problem `45': `loggregator_trafficcontroller_z1/0 (644370e0-7009-4996-b3e8-d286267a6923)' is not running after update. Review logs for failed jobs: loggregator_trafficcontroller
Error resolving problem `46': `hm9000_z1/0 (055cf9ad-839a-4870-b1fc-bf53ee4d8f2a)' is not running after update. Review logs for failed jobs: consul_agent, hm9000_listener, hm9000_analyzer, hm9000_api_server, hm9000_evacuator, hm9000_shredder
Error resolving problem `47': `blobstore_z1/0 (f066fb4b-b356-4234-a0a7-935497d9eacf)' is not running after update. Review logs for failed jobs: consul_agent
Error resolving problem `50': `postgres_z1/0 (3f0de6cf-c543-4280-a518-e544ec142c90)' is not running after update. Review logs for failed jobs: postgres, metron_agent
```

Attaching the debug logs for further reference. 

[task50.txt](https://github.com/cloudfoundry/bosh-lite/files/444576/task50.txt)

**Comment by dpb587-pivotal** [comment]
Have you tried investigating the logs on the failed VMs to check details? Some tips around [here](http://bosh.io/docs/tips.html#failed-job). You could also try recreating the whole deployment with `bosh deploy --recreate` as a last resort.

**Comment by cppforlife** [comment]
@rphukan I believe we fixed this in later versions. If you select `bosh cck --auto` or 'Recreate VM without waiting for processes to start' option if doing cck manually.
