### ISSUE TITLE
"No missing vms to create" when "bosh deploy" my release using bosh-lite

### ISSUE THREAD

**Issue by isisliu** [cloudfoundry/bosh-lite#394]
I have deployed bosh-lite and cloud foundry on my Mac. 
I created my own release successfully, when I deploy my release, the task is done successfully, but "bosh vms", there is no VMs for my release.
I checked "bosh task 37 --debug",  the below logs , 

I, [2016-08-30 07:32:28 #27934] [task:37]  INFO -- DirectorJobRunner: Creating missing V/crete_Ms
I, [2016-08-30 07:32:28 #27934] [task:37]  INFO -- DirectorJobRunner: No missing vms to create

here is my manifest:
name: receivepayment
director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8
release:
  name: receivepayment
  version: 0+dev.1
compilation:
  workers: 1
  network: default
  cloud_properties:
    name: random
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1
networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
    reserved:
    - 10.244.0.9
    static:
    - 10.244.0.10
  - cloud_properties:
      name: random
    range: 10.244.0.12/30
    reserved:
    - 10.244.0.13
    static:
    - 10.244.0.14
  - cloud_properties:
      name: random
    range: 10.244.0.16/30
    reserved:
    - 10.244.0.17
    static:
    - 10.244.0.18
  - cloud_properties:
      name: random
    range: 10.244.0.20/30
    reserved:
    - 10.244.0.21
    static:
    - 10.244.0.22
  - cloud_properties:
      name: random
    range: 10.244.0.24/30
    reserved:
    - 10.244.0.25
    static:
    - 10.244.0.26
  - cloud_properties:
      name: random
    range: 10.244.0.28/30
    reserved:
    - 10.244.0.29
    static:
    - 10.244.0.30
  - cloud_properties:
      name: random
    range: 10.244.0.32/30
    reserved:
    - 10.244.0.33
    static:
    - 10.244.0.34
  - cloud_properties:
      name: random
    range: 10.244.0.36/30
    reserved:
    - 10.244.0.37
    static:
    - 10.244.0.38
  - cloud_properties:
      name: random
    range: 10.244.0.40/30
    reserved:
    - 10.244.0.41
    static:
    - 10.244.0.42
  - cloud_properties:
      name: random
    range: 10.244.0.44/30
    reserved:
    - 10.244.0.45
    static:
    - 10.244.0.46
  - cloud_properties:
      name: random
    range: 10.244.0.48/30
    reserved:
    - 10.244.0.49
    static:
    - 10.244.0.50
  - cloud_properties:
      name: random
    range: 10.244.0.52/30
    reserved:
    - 10.244.0.53
    static:
    - 10.244.0.54
  - cloud_properties:
      name: random
    range: 10.244.0.56/30
    reserved:
    - 10.244.0.57
    static:
    - 10.244.0.58
  - cloud_properties:
      name: random
    range: 10.244.0.60/30
    reserved:
    - 10.244.0.61
    static:
    - 10.244.0.62
  - cloud_properties:
      name: random
    range: 10.244.0.64/30
    reserved:
    - 10.244.0.65
    static:
    - 10.244.0.66
  - cloud_properties:
      name: random
    range: 10.244.0.68/30
    reserved:
    - 10.244.0.69
    static:
    - 10.244.0.70
  - cloud_properties:
      name: random
    range: 10.244.0.72/30
    reserved:
    - 10.244.0.73
    static:
    - 10.244.0.74
  - cloud_properties:
      name: random
    range: 10.244.0.76/30
    reserved:
    - 10.244.0.77
    static:
    - 10.244.0.78
  - cloud_properties:
      name: random
    range: 10.244.0.80/30
    reserved:
    - 10.244.0.81
    static:
    - 10.244.0.82
  - cloud_properties:
      name: random
    range: 10.244.0.84/30
    reserved:
    - 10.244.0.85
    static:
    - 10.244.0.86
  - cloud_properties:
      name: random
    range: 10.244.0.88/30
    reserved:
    - 10.244.0.89
    static:
    - 10.244.0.90
  - cloud_properties:
      name: random
    range: 10.244.0.92/30
    reserved:
    - 10.244.0.93
    static:
    - 10.244.0.94
  - cloud_properties:
      name: random
    range: 10.244.0.96/30
    reserved:
    - 10.244.0.97
    static:
    - 10.244.0.98
  - cloud_properties:
      name: random
    range: 10.244.0.100/30
    reserved:
    - 10.244.0.101
    static:
    - 10.244.0.102
  - cloud_properties:
      name: random
    range: 10.244.0.104/30
    reserved:
    - 10.244.0.105
    static:
    - 10.244.0.106
  - cloud_properties:
      name: random
    range: 10.244.0.108/30
    reserved:
    - 10.244.0.109
    static:
    - 10.244.0.110
  - cloud_properties:
      name: random
    range: 10.244.0.112/30
    reserved:
    - 10.244.0.113
    static:
    - 10.244.0.114
  - cloud_properties:
      name: random
    range: 10.244.0.116/30
    reserved:
    - 10.244.0.117
    static:
    - 10.244.0.118
  - cloud_properties:
      name: random
    range: 10.244.0.120/30
    reserved:
    - 10.244.0.121
    static:
    - 10.244.0.122
  - cloud_properties:
      name: random
    range: 10.244.0.124/30
    reserved:
    - 10.244.0.125
    static:
    - 10.244.0.126
  - cloud_properties:
      name: random
    range: 10.244.0.128/30
    reserved:
    - 10.244.0.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.132/30
    reserved:
    - 10.244.0.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.136/30
    reserved:
    - 10.244.0.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.140/30
    reserved:
    - 10.244.0.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.144/30
    reserved:
    - 10.244.0.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.148/30
    reserved:
    - 10.244.0.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.152/30
    reserved:
    - 10.244.0.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.156/30
    reserved:
    - 10.244.0.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.160/30
    reserved:
    - 10.244.0.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.164/30
    reserved:
    - 10.244.0.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.168/30
    reserved:
    - 10.244.0.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.172/30
    reserved:
    - 10.244.0.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.176/30
    reserved:
    - 10.244.0.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.180/30
    reserved:
    - 10.244.0.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.184/30
    reserved:
    - 10.244.0.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.188/30
    reserved:
    - 10.244.0.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.192/30
    reserved:
    - 10.244.0.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.196/30
    reserved:
    - 10.244.0.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.200/30
    reserved:
    - 10.244.0.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.204/30
    reserved:
    - 10.244.0.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.208/30
    reserved:
    - 10.244.0.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.212/30
    reserved:
    - 10.244.0.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.216/30
    reserved:
    - 10.244.0.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.220/30
    reserved:
    - 10.244.0.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.224/30
    reserved:
    - 10.244.0.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.228/30
    reserved:
    - 10.244.0.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.232/30
    reserved:
    - 10.244.0.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.236/30
    reserved:
    - 10.244.0.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.240/30
    reserved:
    - 10.244.0.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.244/30
    reserved:
    - 10.244.0.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.248/30
    reserved:
    - 10.244.0.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.0.252/30
    reserved:
    - 10.244.0.253
    static: []
resource_pools:
  - name: common
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    env:
      bosh:
        password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
    cloud_properties:
      name: random
jobs: 
- name: deploy-payment
  template: deploy-payment
  lifecycle: errand
  instances: 1
  resource_pool: common
  persistent_disk: 1024
  default_networks:
    - name: default
  networks: 
    - name: default
      static_ips:
      - 10.244.0.58
properties: 
  domain: bosh-lite.com
  ssl:
    skip_cert_verify: true
  receivepayment:
    app_memory: 2048M
    app_disk: 1024M
    app_numOfInstances: 1
    debug: 
    deployment: STAGING
    region: us-south
    regionEnabled: true
    uaaUsername: 
    uaaPassword: 
    dbPassword: 
    dbUser: receive-payment-stage
    dbUrl: receive-payment-stage
    authorizedUsers: 
    authorizedScope: openid
    user: admin
    password: admin
    org: 
    space: 
    quota: q2GB

**Comment by dpb587-pivotal** [comment]
Right now your `deploy-payment` job/instance group is configured with a `lifecycle` as an `errand`. This means the VM will only exist when you run `bosh run errand deploy-payment`. This [link](https://bosh.io/docs/deployment-manifest.html#jobs) documents the `lifecycle` property if you'd like a bit more detail.

Also, next time you need to paste some code/manifest snippets, it's easier to read if you use code fences or indentation to retain newlines and spacing. For example...

    ```yaml
    name: receivepayment
    networks:
      - name: default
        subnets:
    ...
    ```

**Comment by isisliu** [comment]
many thanks @dpb587-pivotal , issue resolved. Will use code fences next time if paste some code :)
