### ISSUE TITLE
add-route doesn't add the routes correctly

### ISSUE THREAD

**Issue by Freyert** [cloudfoundry/bosh-lite#395]
Not sure exactly what's going on here, but add-route never adds the routes correctly. On my system the Virtualbox gateway is 192.168.59.1. So that's the first thing I know to change.

`Local -> 192.168.59.1 -> 192.168.59.4`

Then I was unable to `bosh ssh` into my jobs all of which are on the 10.254.0.0/16 network and not the expected 10.244.0.0/16 network. It took some guess work to figure out that instead of also using the VirtualBox gateway 192.168.59.1 I should use the Bosh directory IP address of 192.168.59.4.

`Local -> 192.168.59.4 -> 10.254.0.0/16`

```
Vagrant
Installed Version: 1.7.4
Latest Version: 1.8.5

VirtualBox
5.0.26r108824

Bosh Lite
cloudfoundry/bosh-lite (virtualbox, 9000.126.0)
```

**Comment by dpb587-pivotal** [comment]
Is this the same issue or environment as [#387](https://github.com/cloudfoundry/bosh-lite/issues/387#issuecomment-242746553)?

**Comment by Freyert** [comment]
Yes @dpb587-pivotal. It wasn't getting any notice there, and since it was a closed issue I felt it would be more appropriate to open a new one.

**Comment by ipeacocks** [comment]
Default IP for bosh-lite instance is `192.168.50.4`.  This IP is hardcoded in `bin/add-route` script. So if you change default IP for bosh-lite vm, you also need to adjust bin/add-route` script.

**Comment by GrahamAka** [comment]
If your Vagrant host is running on Windows then the scripts under the /vagrant/bin folder have DOS style line terminators, so the script fails. This is because /vagrant actually maps back to the bosh-lite installation on the host machine.

If you `sudo apt-get install dos2unix` and then `dos2unix add-route` then the script will succeed.
