### ISSUE TITLE
Increase director worker count

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-lite#396]
We'd like to increase the worker count to something greater than 3 for the bosh director. Are there any reservations against increasing this number? Would a pull request increasing the worker count to `11` and setting `enable_dedicated_status_worker` be well received?

**Comment by cppforlife** [comment]
@zankich 11 doesnt make sense as a default since that will be a lot of extra ruby processes doing nothing.

**Comment by zankich** [comment]
@cppforlife what number would you prefer? I submitted a PR with 11 https://github.com/cloudfoundry/bosh-lite/pull/398, but I can change it to a lower number.

**Comment by dpb587-pivotal** [comment]
Closing - bumped workers to 4 a while back, and settings are now more configurable via [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) ops.
