### ISSUE TITLE
vagrant up issue

### ISSUE THREAD

**Issue by bartstinson** [cloudfoundry/bosh-lite#397]
Trying to install a standalone CF on Windows machine using Hyper-V. Getting the following issue when running 

vagrant up --provider=hyperv

Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: hyperv
    default: Box Version: >= 0
==> default: Loading metadata for box 'cloudfoundry/bosh-lite'
    default: URL: https://atlas.hashicorp.com/cloudfoundry/bosh-lite

Vagrant version = 1.8.5

Is only VirtualBox supported?

Thanks.

**Comment by dpb587-pivotal** [comment]
Sorry, only VirtualBox and AWS boxes of bosh-lite are currently published. They're available from https://atlas.hashicorp.com/cloudfoundry/boxes/bosh-lite.
