### ISSUE TITLE
Unable to target bosh-lite VM on OS X Sierra

### ISSUE THREAD

**Issue by clingmann** [cloudfoundry/bosh-lite#406]
I've updated ruby to a newer version and set target with rbenv and suggested in other closed thread with no success.

Leto:bosh-lite chad$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

Leto:bosh-lite chad$ bosh -v
BOSH 1.3262.24.0
Leto:bosh-lite chad$ which bosh
/Users/chad/.rbenv/shims/bosh

Leto:bosh-lite chad$ bosh target 192.168.50.4 lite
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure)

nc -z 192.168.50.4 25555
Connection to 192.168.50.4 port 25555 [tcp/*] succeeded!

Leto:bosh-lite chad$ curl -vk https://192.168.50.4:25555/info
*   Trying 192.168.50.4...
* Connected to 192.168.50.4 (192.168.50.4) port 25555 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: 192.168.50.4
> GET /info HTTP/1.1
> Host: 192.168.50.4:25555
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 07 Nov 2016 23:39:15 GMT
< Content-Type: application/json
< Content-Length: 358
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< 
* Connection #0 to host 192.168.50.4 left intact
{"name":"Bosh Lite Director","uuid":"fb70f16a-4d6f-41f8-bc2e-0181a03dff18","version":"1.3262.3.0 (00000000)","user":null,"cpi":"warden_cpi","user_authentication":{"type":"basic","options":{}},"features":{"dns":{"status":false,"extras":{"domain_name":null}},"compiled_package_cache":{"status":true,"extras":{"provider":"local"}},"snapshots":{"status":false}}}Leto:bosh-lite chad$ 

SSH in via vagrant has no issue, so doesn't appear to be a routing issue.

Leto:bosh-lite chad$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-42-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
vagrant@bosh-lite:~$ 

Anyone have any suggestions for troubleshooting bosh connection?

**Comment by dpb587-pivotal** [comment]
Please see https://github.com/cloudfoundry/bosh/issues/1322 for some suggestions. Perhaps try `brew install ruby` and use that ruby?

**Comment by clingmann** [comment]
Ok I manually had installed the latest ruby, and had set my system using rbenv to use this latest version as shown above.  instructions from here:  https://gorails.com/setup/osx/10.12-sierra

I ran the command 'brew install ruby' and like magic it is now working for bosh target. I was not using the system ruby, which was being blamed as the culprit,
 
Leto:~ chad$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
Leto:~ chad$ which ruby
/Users/chad/.rbenv/shims/ruby

I'm not sure what configuration or link the brew install is creating, but it is now working none the less. Thank you!
