### ISSUE TITLE
No loop device support in the latest-bosh-stemcell-warden.tgz

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/bosh-lite#41]
I tried to deploy MySQL service in a bosh-lite created CF? MySQL failed to start with error message:

   Tue Oct 22 07:46:05 UTC 2013 ERROR: fail to get one free loop device

This message is from /var/vcap/jobs/mysql_node/bin/create_mysql_tmp_dir , below line: 

   loop_dev=`losetup -f`

I executed "losetup -f" in the MySQL VM (it's actually a Warden instance), and got below result:
root@31a6a515-e2cf-43d9-8d76-88ea4993f4b4:/var/vcap/jobs/mysql_node/bin# losetup -f
losetup: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)

Does that mean the stemcell need to be recompiled?

**Comment by ryanmoran** [comment]
@syslxg we are looking into managing quotas for our own filesystems on a warden container. We want to be able to create an ext4 FS and then use a loop device to mount it. We discovered this thread and were wondering if you knew whether the state of this functionality had changed to allow something like this.  

cc: @rosenhouse
