### ISSUE TITLE
Login credentials for Bosh-lite VirtualBox Ubuntu image

### ISSUE THREAD

**Issue by subsolar00** [cloudfoundry/bosh-lite#419]
I am currently running through the deployment process for a Lite development environment for BOSH. I have installed BOSH Lite, Vagrant and VirtualBox but have run into an issue with credentials for the Ubuntu image provided in the installation.  Documentation says "_When prompted to log in, use admin/admin_" however these do not appear to be working. I have tried nearly all combinations of standard admin passwords without luck. Would anyone be able to help?

Vagrant up output
C:\HashiCorp\bosh-lite>vagrant up --provider=virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 9000.137.0
==> default: Loading metadata for box 'cloudfoundry/bosh-lite'
    default: URL: https://atlas.hashicorp.com/cloudfoundry/bosh-lite
==> default: Adding box 'cloudfoundry/bosh-lite' (v9000.137.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/cloudfoundry/boxes/bosh-lite/versions/9000.137.0/providers/virtualbox.box
    default: Progress: 100% (Rate: 12.2M/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'cloudfoundry/bosh-lite' (v9000.137.0) for 'virtualbox'!
==> default: Importing base box 'cloudfoundry/bosh-lite'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'cloudfoundry/bosh-lite' is up to date...
==> default: Setting the name of the VM: bosh-lite_default_1487095651043_66729
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/HashiCorp/bosh-lite

VirtualBox
Ubuntu 14.04.4 LTS agent-id-bosh-0 tty1

agent-id-bosh-0 login:???

**Comment by ipeacocks** [comment]
go to bosh-lite dir (which you clonned) and try:

```# vagrant ssh```
