### ISSUE TITLE
bosh-lite tasks queued forever

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/bosh-lite#422]
I am running bosh-lite on my Macbook Pro late 2012 using the latest version of Vagrant & Virtualbox.
Every Task i start will remain in the queued state forever.
I already recreated the vm, reinstalled Vagrant & Virtualbox but none of this could solve my problem. Also i made sure that i am logged in as admin and that i am targeting the director.

**Comment by cppforlife** [comment]
@gdenn this is related to a race condition between scripts inside the vm. currently if you are hitting this problem, work around is to run monit restart all inside the vm after it started up. alternatively you can give a try: https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md
