### ISSUE TITLE
SSL certificate for Director is invalid on AWS

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-lite#424]
I did `vagrant up --provider=aws` and when I try to target it with the new BOSH CLI, which requires SSL validation, it complains that the cert was signed for 192.168.50.4 instead of the elastic IP associated with my Director VM.  Will BOSH-Lite on AWS essentially be deprecated once the Ruby BOSH CLI is deprecated?

**Comment by cppforlife** [comment]
> Will BOSH-Lite on AWS essentially be deprecated once the Ruby BOSH CLI is deprecated?

what will be eventually deprecated is vagrant integration; however, bosh lite will live on to work with bosh create-env.

> ...when I try to target it with the new BOSH CLI, which requires SSL validation, it complains that the cert was signed for 192.168.50.4 instead of the elastic IP associated with my Director VM

https://github.com/cloudfoundry/bosh-lite#ca-certificate. cert should work with *.sslip.io which should allow targeting new new/old cli.
