### ISSUE TITLE
I could not set the API endpoint 

### ISSUE THREAD

**Issue by khirod12** [cloudfoundry/bosh-lite#433]
redeploy cf-release
redeploy diego-release

bin/add-route
recreate vms using bosh cck

All the vms and instances are up and running
But , when I tried to login . it failed as no API endpoint set . 

cf login --skip-ssl-validation -u admin

API endpoint> api.bosh-lite.com
FAILED
Server error, status code: 404, error code: 0, message: 
khirod@khirod-cf:~/Workspace/bosh-lite$ cf login --skip-ssl-validation -u admin -p admin

API endpoint> 

Thanks,
Khirod

**Comment by khirod12** [comment]
cf api --skip-ssl-validation https://api.bosh-lite.com
Setting api endpoint to https://api.bosh-lite.com...
API endpoint not found at 'https://api.bosh-lite.com'
FAILED

**Comment by dpb587-pivotal** [comment]
Closing - sounds like you were able to figure it out in #432
