### ISSUE TITLE
bosh upload-stemcell gives error: Expected non-empty Director URL 

### ISSUE THREAD

**Issue by ramyasg** [cloudfoundry/bosh-lite#436]
**'bosh upload-stemcell <file.tgz>'** 
gives error: 

> Expected non-empty Director URL 

We followed the link - 'https://bosh.io/docs/uploading-stemcells.html' to generate stemcell, upload director to vSphere and then when we are trying to upload custom stemcell to the director deployed on vsphere (IAAS), we are getting error on the command prompt -  Expected non-empty Director URL

**Comment by xtreme-andrew-su** [comment]
@ramyasg did you specify the environment you're targeting?
`bosh -e <environment> upload-stemcell <file.tgz>`

**Comment by ramyasg** [comment]
Thanks @xtreme-andrew-su. We added the environment and it started working.
