### ISSUE TITLE
"bosh create-env concourse-lite.yml" fails while creating VM

### ISSUE THREAD

**Issue by SaurabhQA** [cloudfoundry/bosh-lite#440]
Hi,

I am trying to spin up Concourse using "bosh create-env concourse-lite.yml".
I am using a Ubuntu VM to setup Concourse.

Below is the error seen:
Started deploying
  Creating VM for instance 'concourse/0' from stemcell 'sc-6196df8a-6e26-411f-70b5-0cc0466a5adf'... Failed (00:01:18)
Failed deploying (00:01:18)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'concourse/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-6196df8a-6e26-411f-70b5-0cc0466a5adf':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{f100e8f7-cb3b-41f3-4c06-e2cd0a8f1f09}}': Starting VM: Retried '30' times: Running command: 'VBoxManage startvm vm-2989f2b5-e123-48c5-69dd-8df6f88799d2 --type headless', stdout: 'Waiting for VM \"vm-2989f2b5-e123-48c5-69dd-8df6f88799d2\" to power on...\n', stderr: 'VBoxManage: error: The virtual machine 'vm-2989f2b5-e123-48c5-69dd-8df6f88799d2' has terminated unexpectedly during startup with exit code 1 (0x1)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine\n': exit status 1","ok_to_retry":false}

Exit code 1

**Comment by dpb587-pivotal** [comment]
Hi - please try [these recommendations](https://github.com/hashicorp/vagrant/issues/8687#issuecomment-339014825) from the hashicorp/vagrant repository and see if they help.

**Comment by SaurabhQA** [comment]
Thanks, I tried reloading the vboxdrv, vboxpci, vbox* kernel modules. After that I am seeing a different error.

Deploying:
  Creating instance 'concourse/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-6196df8a-6e26-411f-70b5-0cc0466a5adf':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{1583b4e0-7ff8-4744-4f2e-c8386779aaab}}': Starting VM: Retried '30' times: Running command: 'VBoxManage startvm vm-9d80545c-a808-4236-4a61-93bf3df6ab8e --type headless', stdout: 'Waiting for VM \"vm-9d80545c-a808-4236-4a61-93bf3df6ab8e\" to power on...\n', stderr: 'VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole\n': exit status 1","ok_to_retry":false}

Exit code 1

**Comment by fordprior** [comment]
Seeing the same `VT-x is not available` error on the `create-env` step of my bosh deploy.

**Comment by dpb587-pivotal** [comment]
`VT-x is not available` often means the Virtualization of the host's BIOS-level configuration has not been enabled. Try updating the host configuration and trying again.

**Comment by KrisKobylinski** [comment]
Once I have enabled Hardware Virtualization (VT-x) on my VM I've got rid of the error 'VT-x is not available'.
