### ISSUE TITLE
cf api --skip-ssl-validation https://a.b.c.d.xip.io fails

### ISSUE THREAD

**Issue by TCSCMAPIVOTAL** [cloudfoundry/bosh-lite#441]
I am using bosh-lite on AWS, deployed the s/w on an ec2 instance (allocated static IP a.b.c.d) using vagrant up provider=aws with
BOSH_LITE_ELASTIC_IP=a.b.c.d

from a different EC2 instance w.x.y.z
#bosh target a.b.c.d boshlite ----- works fine
# bosh vms ---- works fine
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+---------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs          | DNS A records |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+---------------+
| api_z1/0 (1fcdf6fb-f047-422d-a33e-b06a9b14358e)                           | running | n/a | large_z1  | 10.244.0.138 | n/a           |
| blobstore_z1/0 (e9053ac7-0bc0-4485-b457-b3c134cab57e)                     | running | n/a | medium_z1 | 10.244.0.130 | n/a           |
| consul_z1/0 (70a69f56-646d-4f90-b31a-d371ce4b5941)                        | running | n/a | small_z1  | 10.244.0.54  | n/a           |
| doppler_z1/0 (6c715ffb-fa05-44fb-b134-5d9ab88a0419)                       | running | n/a | medium_z1 | 10.244.0.142 | n/a           |
| etcd_z1/0 (7d48a6f1-8fff-4fa4-8245-e2360f967d6a)                          | running | n/a | large_z1  | 10.244.0.42  | n/a           |
| ha_proxy_z1/0 (31c4ee4f-8ffd-4de4-909d-ea3820a5369e)                      | running | n/a | router_z1 | 10.244.0.34  | n/a           |
| loggregator_trafficcontroller_z1/0 (ccebf942-c489-4fb4-b874-37f4c4385853) | running | n/a | small_z1  | 10.244.0.146 | n/a           |
| nats_z1/0 (f3be8e0c-6ee2-447a-bb09-a4831c0add62)                          | running | n/a | medium_z1 | 10.244.0.6   | n/a           |
| postgres_z1/0 (cfe4184e-110f-43c6-b468-a1e9726ef824)                      | running | n/a | medium_z1 | 10.244.0.30  | n/a           |
| router_z1/0 (4051beb4-0a55-454c-8931-1e594f2cadff)                        | running | n/a | router_z1 | 10.244.0.22  | n/a           |
| uaa_z1/0 (f7cc539a-69be-4fc5-898d-d8a1d547cf2c)                           | running | n/a | medium_z1 | 10.244.0.134 | n/a           |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+---------------+

# cf api --skip-ssl-validation https://a.b.c.d.xip.io
Setting api endpoint to https://a.b.c.d.xip.io...
Request error: Get https://a.b.c.d.xip.io/v2/info: dial tcp a.b.c.d:443: getsockopt: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED

# ping -a a.b.c.d.xip.io --- works fine

Vagrant ssh to a.b.c.d works fine and from there I can work on the cloud foundry without any issue.
(I have all the required env variables set on IP w.x.y.z)

My requirement is to assign a public DNS (route 53) for the cloud foundry - ha_proxy_z1/0 and access deployed apps from internet

**Comment by dpb587-pivotal** [comment]
We are no longer maintaining bosh-lite, so I would recommend the following alternatives...

 * [cloudfoundry/bosh-deployment](https://bosh.io/docs/bosh-lite.html) - for provisioning recent versions of director and stemcells
 * [cloudfoundry/cf-deployment](https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/bosh-lite) - for deploying recent CF to bosh-lite environments

Feel free to give those a try and follow up in one of those repositories if you run into issues using them.
